### ISSUE TITLE
Update phone # in email with subject "Action needed: Complete your enrollment"

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/connectApp#100]
I received an email with the subject line "Action needed: Complete your enrollment". In this email the phone number is listed as "1-800-xxx-xxxx". This phone number should be "1-800-462-6621" because the email is being sent to a recruit and someone who is not yet a verified participant.

**Comment by cunnaneaq** [comment]
Correction:  The phone number should be "1-866-462-6621"

**Comment by bhaumik55231** [comment]
This needs to be updated in the notification schemas that Amelia is working on.

**Comment by robertsamm** [comment]
@bhaumik55231 The User Profile notification specs have been updated with the recruit CSC phone number. The updated JSON files can be found here: https://nih.app.box.com/folder/136029031396

**Comment by cunnaneaq** [comment]
![Screen Shot 2021-07-19 at 3 27 18 PM](https://user-images.githubusercontent.com/83971268/126219408-eae6042d-d207-44bb-bec8-b9c3b225c106.png)

Attached is a screenshot of the email I'm referring to, if needed.

**Comment by bhaumik55231** [comment]
Hi @cunnaneaq, I have modified them in the stage environment. Please use the stage for email testing.

**Comment by cusackjm** [comment]
confirmed phone number in email is updated
