### ISSUE TITLE
PWA Locked Up 

### ISSUE THREAD

**Issue by eibergenr** [episphere/connectApp#102]
In attempting to do this scenario:  

SCENARIO:Kelly   Testing-Comreg receives invitation in the mail and wants to participate.The next day, she can't find the letter, so googles and enrolls with "I don't have a PIN". Later, she finds the letter and enrolls  again with exact information using her PIN using her work email.

When we attempted to login with her second email kellytesting@sharklasers.com with password Connect2021, PWA locked up and showed the following message:  You have a new form to sign.  You have been withdrawn from Connect per your request.

We were unable to sign out, used task manager to kill the app, re-opened app, and the locked up page auto-opened.  Note:  I think retaining the login is problematic as a whole.

I'm not sure why this happened, unless somehow the PWA app knew that Kelly Testing was a duplicate.  

Next steps:  I will restart my device and see if that will clear it up.  Update a complete restart did not clear it from my browser.  Only way out was to kill task.

![ConnectAppLocked](https://user-images.githubusercontent.com/80000721/119506952-03861500-bd34-11eb-9c52-b4dc1e5674e8.jpg)

**Comment by hzhao392** [comment]
@eibergenr we had a bad build last week during testing, I think this was related to it. It should be fixed now
