### ISSUE TITLE
Change subject line of email sent with verification link after sign up

### ISSUE THREAD

**Issue by depietrodeanna** [episphere/connectApp#106]
Change subject line of email sent from MyConnect with verification link after someone signs up with their email to: **“Verify your email for the Connect for Cancer Prevention Study.”**  

Previously this was "Verify your email for Connect for Cohort Study"

**Comment by cusackjm** [comment]
![image](https://user-images.githubusercontent.com/85582895/126176635-3c5a05d6-7d84-4a78-957b-b48c5dcce98a.png)

edit successful

**Comment by bhaumik55231** [comment]
It has been modified to "Verify your email for the Connect for Cancer Prevention Study.". Closing the issue, please reopen if you have any problem.
