### ISSUE TITLE
Edit closing salutation of email sent with verification link after sign up

### ISSUE THREAD

**Issue by depietrodeanna** [episphere/connectApp#107]
Edit signature in closing of email sent with verification link from "Your Connect for Cohort Study team" to **the Connect team**

**Comment by bhaumik55231** [comment]
This needs to updated in the notification schemas that Amelia is working on.

**Comment by bhaumik55231** [comment]
Hi @depietrodeanna should not it be **Your Connect for Cancer Prevention Study team**, same as what we have in the email subjects - https://github.com/episphere/connectApp/issues/106.

**Comment by cusackjm** [comment]
confirmed fix

**Comment by cusackjm** [comment]
![image](https://user-images.githubusercontent.com/85582895/126339935-7d727f3b-be87-4aba-84bd-c59912c50d85.png)
 
Signature needs to be "Your Connect for Cancer Prevention Study Team"

**Comment by bhaumik55231** [comment]
Hi @cunnaneaq, @cusackjm can we do such testing in stage and not in dev? the stage has the latest configs and is closest to the prod.

**Comment by cusackjm** [comment]
@bhaumik55231 do you know if NCI is listed as one of the sites on the staging site? the last i checked it was not listed. If it isn't, should we select one of the sites?

**Comment by bhaumik55231** [comment]
@cusackjm how about we use the University of Chicago Medicine as a test site as they will be the last site to go into production.

**Comment by bhaumik55231** [comment]
Let's discuss this in tomorrow's launch stand-up.

**Comment by cusackjm** [comment]
![image](https://user-images.githubusercontent.com/85582895/126504029-eb4483c1-bb9b-482f-9261-6500814edbfa.png)

The first sentence of the email and email signature also need to be changed for the resetting password email

**Comment by cunnaneaq** [comment]
confirmed fixed - tested in stage
