### ISSUE TITLE
Mandatory Change: Add Warning Banner Notification on Home Page at Sign In

### ISSUE THREAD

**Issue by miagaudet** [episphere/connectApp#108]
Full Message Required:
You are accessing a U.S. Government web site which may contain information that must be protected under the U.S. Privacy Act or other sensitive information and is intended for Government authorized use only. Unauthorized attempts to upload information, change information, or use of this web site may result in disciplinary action, civil, and/or criminal penalties. Unauthorized users of this web site should have no expectation of privacy regarding any communications or data processed by this web site. Anyone accessing this web site expressly consents to monitoring of their actions and all communication or data transitioning or stored on or related to this web site and is advised that if such monitoring reveals possible evidence of criminal activity, NIH may provide that evidence to law enforcement officials.

If space is an issue (mobile devices?) you can use this abbreviated message: 
Unauthorized/improper use is prohibited and may result in disciplinary action and/or civil and criminal penalties. At any time, and for any lawful Government purpose, the government may monitor, record, and audit your system usage and/or intercept, search, seize, disclose, or use any communication or data transiting or stored on this system. There is no reasonable expectation of privacy. 

For example like when we log in with our PIV cards (you can take the font size and color from these pages). 

For our security review, please take a screenshot when implemented into the PWA.

**Comment by cunnaneaq** [comment]
<img width="364" alt="Screen Shot 2021-06-22 at 1 06 03 PM" src="https://user-images.githubusercontent.com/83971268/122969475-af824680-d35a-11eb-9bf8-c5dea27603b4.png">

Confirming that this is implemented.  Please see attached screenshot.  I can see the full text when using my laptop and mobile device.
