### ISSUE TITLE
Zip code can be all letters, street can be all numbers, and city can be all numbers without errors

### ISSUE THREAD

**Issue by lorenasandoval88** [episphere/connectApp#109]
![image](https://user-images.githubusercontent.com/43822820/119871064-147b8580-bef0-11eb-8b2c-2af753b54809.png)

**Comment by cusackjm** [comment]
![image](https://user-images.githubusercontent.com/85582895/126172389-cb0f308f-a18e-453c-895c-0076568765a5.png)

shows Zip code error, but address and city can still be numbers

**Comment by cusackjm** [comment]
![image](https://user-images.githubusercontent.com/85582895/126172720-26bcd2db-68ab-4bae-b142-67f191bfe1c1.png)
