### ISSUE TITLE
Login with Token URL

### ISSUE THREAD

**Issue by eibergenr** [episphere/connectApp#110]
I'm wondering if you could please confirm what we should be expecting upon login with URL with token.  We are using the following:  https://episphere.github.io/connectApp/?token=<TOKEN> and receive the following:
![image](https://user-images.githubusercontent.com/80000721/120518664-6a8c7500-c397-11eb-8727-44a6c2626af5.png)

Then I entered email and password, verified email, and was prompted to sign in.  I then entered email and password and was prompted to enter my PIN.

Is this what you would expect?  If so, what purpose is the token?  Thanks!

**Comment by eibergenr** [comment]
@bhaumik55231 What are your thoughts on this question or who should I ask? Thanks!

**Comment by anthonypetersen** [comment]
Don't believe this is relevant anymore with link branding...
