### ISSUE TITLE
Add screens to electronic consent

### ISSUE THREAD

**Issue by depietrodeanna** [episphere/connectApp#111]
There are a few additional screens to be added to the electronic consent piece of the PWA on Indigenous Peoples. Please use this link, which contains the screens in the appropriate order (these come right before the consent form and HIPAA):

https://nih.box.com/s/f0efuokowaxl4bp1wa4qbmxmey2cr3km

The title on the progress bar should be: Indigenous Peoples

**Comment by cusackjm** [comment]
Confirmed in testing that screens have been added.
