### ISSUE TITLE
Add language to user profile section after "Can we text this number?"

### ISSUE THREAD

**Issue by depietrodeanna** [episphere/connectApp#113]
In user profile, we ask if we can text the phone number(s) they provide. 
We need to add: “Text message charges may apply” following each instance of “Can we text this number?”

**Comment by cusackjm** [comment]
I see "can we text this number" in the My profile section while signing up, but once signed up and verified, "can we text this number" in the My profile section is not shown. 
![image](https://user-images.githubusercontent.com/85582895/123809566-b57aa900-d8bf-11eb-80ec-7fe6ab6859af.png)

**Comment by cunnaneaq** [comment]
Clarification from Deanna, this language only needs to be added while someone is creating a user profile and not after it has already been created.  Please see the attached screenshot for confirmation that it has been added.
<img width="890" alt="Screen Shot 2021-07-12 at 2 09 14 PM" src="https://user-images.githubusercontent.com/83971268/125342563-06a88500-e323-11eb-86f1-e644903f65b2.png">
