### ISSUE TITLE
Test obscure characters in name for sign up

### ISSUE THREAD

**Issue by depietrodeanna** [episphere/connectApp#117]
Tilde, a/e letter, etc. Accepted? Error message?

**Comment by cunnaneaq** [comment]
Tried a first name with the ae digraph and last name with a tilde over an n.  I received an error message for both stating "You first (last) name should contain only upper and lower case letters.  Please do not use numbers or special characters". Should this be permissible?  This may prevent someone from enrolling.

**Comment by cusackjm** [comment]
Confirmed able to sign up with name as Noël
