### ISSUE TITLE
Changing the name of the “Samples” page to “My Samples” or “Donate Samples”

### ISSUE THREAD

**Issue by cusackjm** [episphere/connectApp#118]
Changing the name of the “Samples” page to “My Samples” or “Donate Samples” (similar to how we changed “Payment” to “My Payment”)

**Comment by cunnaneaq** [comment]
![Screen Shot 2021-08-10 at 9 08 12 AM](https://user-images.githubusercontent.com/83971268/128872337-9f23b62e-2020-4ec9-9f1f-47e401234ef2.png)
