### ISSUE TITLE
Smoother & more transparent transition to eConsent from “how did you hear about the study” page

### ISSUE THREAD

**Issue by cusackjm** [episphere/connectApp#119]
Smoother and more transparent transition to eConsent from “how did you hear about the study” page. Awkward and abrupt as is to go from that question to the first consent screen, which has the rhetorical question, “What is the Connect for Cancer Prevention Study?” There is also no way to go back once you’ve made it to the eConsent screens. (DD TO CREATE LANGUAGE)

**Comment by depietrodeanna** [comment]
Add this language at the bottom of the "how did you hear about the study" question page near the submit/next button. Or, create a separate page that displays this message between the 'how did you hear about the study' question page and the first eConsent screen (called "What is the Connect for Cancer Prevention Study?"

The next screens will take you through the informed consent process. They explain more about the study and what it means to take part in Connect. At the end, you can read the full informed consent form and electronic health records release form before you decide if you want to join.

**Comment by anthonypetersen** [comment]
Is this something we still want to implement? @depietrodeanna

**Comment by depietrodeanna** [comment]
@anthonypetersen yes.

**Comment by jhflorey** [comment]
<img width="1271" alt="Screenshot 2023-04-25 at 10 23 28 AM" src="https://user-images.githubusercontent.com/24559107/234307812-391c4d77-d360-41c5-9a9b-e218bfd476b2.png">

**Comment by jhflorey** [comment]
Hi @depietrodeanna @anthonypetersen , i do not know if my understanding meets your expectations? Please correct me if i was wrong. Please take a look on 2 images below.


<img width="1321" alt="Screen Shot" src="https://user-images.githubusercontent.com/24559107/234312201-6500c65e-19dc-4d6c-ae43-2a832691c246.png">

<img width="1419" alt="Screen Shot" src="https://user-images.githubusercontent.com/24559107/234312439-b0f58115-23b0-4e80-8807-e4c15cad64e8.png">

**Comment by depietrodeanna** [comment]
@jhflorey The language you added on the how did you hear about this study page looks good. @robertsamm we will need to submit this edit to IRB if it wasn't already added to a prior tracked change version of the screens. I'm going to discuss with Mia tomorrow.

**Comment by depietrodeanna** [comment]
@jhflorey Insert "previous" button on the Welcome to Connect screen to allow the user to return to the how did you hear about the study? page. This ensures consistency with the rest of the educational consent screens that follow.

**Comment by jhflorey** [comment]
Hi @depietrodeanna, I already update UI/UX the transition between two pages (the "How did you hear about this study? (Select all that apply" and the"Welcome" page)
I have test 3 cases here:
1.     When I only select 1 checkbox in the list -> on the api request payload will update 1 selected
2.     When I only select 4 checkboxes in the list -> on the api request payload will update 4 selected
3.     *** When I don't select any checkbox in the list -> on the api request payload will update 0 selected ****[Is this correct with the business requirement? Is the select option (at least 1 selected checkbox) is THE REQUIREMENT ?] *****

**Comment by Davinkjohnson** [comment]
This was in the June Release
