### ISSUE TITLE
Add asterisk next to the line “One phone number is required”

### ISSUE THREAD

**Issue by cusackjm** [episphere/connectApp#121]
Add asterisk next to the line “One phone number is required” to make this more consistent with the other requirements?

**Comment by cunnaneaq** [comment]
Can you please change the color and positioning of the asterisk to look more like the email address one in the screenshot.

![Screen Shot 2021-08-10 at 9 12 50 AM](https://user-images.githubusercontent.com/83971268/128873022-f62e2ce7-0505-4e3d-ac1e-e53c538c6526.png)
