### ISSUE TITLE
Need text explanation for red asterisk next to "who is your healthcare provider?"

### ISSUE THREAD

**Issue by cusackjm** [episphere/connectApp#122]
"Who is your healthcare provider?" Has a red asterisk with no explanation of what this means. To us, this means required, but should we have this written out at underneath the question? Text: *Required underneath question before drop-down list of providers

**Comment by anthonypetersen** [comment]
did this get resolved or did we not come to a conclusion on this?

**Comment by cusackjm** [comment]
@anthonypetersen still no explanation. Going to loop Deanna in

**Comment by cusackjm** [comment]
@anthonypetersen can you add "*Required" in red text underneath 
![image](https://user-images.githubusercontent.com/85582895/186472733-4c0ea365-e018-4b89-b62e-09d3a6aa4ce1.png)

**Comment by cusackjm** [comment]
fixed in dev and stage testing
