### ISSUE TITLE
Message to check email and click link to verify should be broken up into more easy-to-read format

### ISSUE THREAD

**Issue by cusackjm** [episphere/connectApp#123]
Message to check email and click link to verify should be broken up into more easy-to-read format (start a new line for each sentence). 
- Please click the link we sent to your email to verify your contact information.
- Be sure to check your spam folder.

**Comment by cunnaneaq** [comment]
![Screen Shot 2021-08-10 at 10 02 17 AM](https://user-images.githubusercontent.com/83971268/128880927-a55983a3-dc13-403b-bc88-a6c60befe3eb.png)

Looks good!
