### ISSUE TITLE
On enter PIN page, start a new line for each sentence

### ISSUE THREAD

**Issue by cusackjm** [episphere/connectApp#124]
On enter PIN page, start a new line for each sentence. Example:
- Please click the link we sent to your email to verify your contact information.
- Be sure to check your spam folder

**Comment by cunnaneaq** [comment]
If you received a PIN as part of your study invitation, please enter it here.
Your PIN should be 6 characters and will include only numbers and uppercase letters.

![Screen Shot 2021-08-10 at 10 07 34 AM](https://user-images.githubusercontent.com/83971268/128881694-ec772f0e-ea10-46a1-8cea-47d567bd817d.png)

**Comment by cusackjm** [comment]
confirmed 
![image](https://user-images.githubusercontent.com/85582895/128927911-3bcf9aec-b40b-4bd3-9ce3-39ee77c73159.png)

**Comment by cusackjm** [comment]
**Issue still exists. See Aileen's comment above**
![image](https://user-images.githubusercontent.com/85582895/128928099-5ed69cea-9613-47ca-bee9-3626bf4defe2.png)

**Comment by cunnaneaq** [comment]
Done!

![Screen Shot 2021-08-12 at 3 35 40 PM](https://user-images.githubusercontent.com/83971268/129258031-befce86a-13b3-40b6-975b-3e5d0baf427d.png)
