### ISSUE TITLE
Alphabetize list for "how did you hear about the study" question

### ISSUE THREAD

**Issue by cusackjm** [episphere/connectApp#125]
For the "how did you hear about the study" question, the list is too long and not alphabetized. Consider grouping into similar categories. Concerns that people may not bother to sift through and answer. Please alphabetize list

**Comment by cunnaneaq** [comment]
Please see the list alphabetized below:

Another Connect participant
Connect research staff at my health care system
Connect table at public event
Connect website on Cancer.gov
Email or text invitation
Family or friend
Health care system newsletter
Health care system website
Invitation through my patient portal (such as MyChart)
Letter or brochure in mail
Local news, television, or radio station
News article or press release about Connect
Other
Phone call invitation
Physician or other health care staff
Poster, flyer, or sign at my health care system
Recorded message
Social media post (on Facebook, Twitter, Instagram, or other channels)
Video
