### ISSUE TITLE
Error entering DADCANH age, age range *incorrectly* related to respondent's age (not Dad's specified in DADAGE)

### ISSUE THREAD

**Issue by cusackjm** [episphere/connectApp#130]
Responded to A135 [DADAGE] "how old is your father today?" with "70".

When I got to A146 [DADCANCH] "how old was your father when they were first told by a doctor that they had kidney cancer
?" I received an error in trying to enter a "age at diagnosis", which said "value must be less than or equal to 41".

I think the error was "41" because I (as the respondent) reported that I was 41.

**Comment by cunnaneaq** [comment]
The same thing happened to me when entering MOM info.  Please see the scenario below.

[MOM] Is your biological mother still living? --> YES [1]
[MOMAGE] How old is your mother today? --> 90
[MOMCANC] --> Yes [1]
[MOMCANC2] --> Cervical [4], Non-Hodgkin's Lymphoma [12], pancreatic [17]
[MOMCANC3E] --> 45
[MOMCANC3M] --> 20
**[MOMCANC3R] --> 89

**I got an error message when I entered 89 years old, saying that the value had to be less than or equal to 65.  But, 65 is my (the participant's) age, not my mother's.  I entered that she is 89.
