### ISSUE TITLE
Skip pattern for A168 [SIBCANC2] (for Sibling #2) did not skip to [SIBCANC3J]

### ISSUE THREAD

**Issue by cusackjm** [episphere/connectApp#135]
Responded 9 (leukemia) to A168 [SIBCANC2] for sibling #2 of 3 and the next question was not [SIBCANC3J] "how old was your sibling#2 when they were first told by a doctor or other health professional that they had or have leukemia?". Instead was looped back to the nickname for Sibling #3

**Comment by cunnaneaq** [comment]
I had this same issue.  I was not asked about sibling's age at dx of cancer and was brought directly to the intro page about children.
