### ISSUE TITLE
(Account was reset), questionnaire opened to last question, even though none of the responses were filled in

### ISSUE THREAD

**Issue by cusackjm** [episphere/connectApp#136]
not sure if this is because my account was reset but I'm had to click back from the end of the questionnaire to the beginning. None of the responses are filled in, but I was brought to the end of the questionnaire

**Comment by cunnaneaq** [comment]
We determined this was because of the way the PWA functions and stores progress locally but answers are stored in the cloud.  Happens when account are reset.  Should not happen in the field because all of the accounts will be new.
