### ISSUE TITLE
Dashboard after submitting Module 1

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/connectApp#143]
I clicked submit after I completed the Module 1 survey.  My Dashboard is still showing the Module 1 survey in the "To Do" tab rather than the "Completed" tab.  When I click on the START button, my screen is blank.

I'm using Google Chrome, non-incognito.

**Comment by cunnaneaq** [comment]
Similar to the issue Julie reported in #134

**Comment by Davinkjohnson** [comment]
Believe this is an older issue. please re-test.

**Comment by cusackjm** [comment]
Confirmed completed questionnaires are out of "to do" tab and in the "completed" tab
