### ISSUE TITLE
[HRMED3] and [HRMED4] Not Asked

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/connectApp#144]
[HRMED] Have you ever used medication to treat thinning hair or hair loss? --> Yes [1]
[HRMED2] What medication did you use to treat thinning hair or hair loss? (Select all that apply) --> Finasteride [1]

My next questions should have been [HRMED3] and [HRMED4] which ask "How old were you when you first/last started using medication to treat thinning hair or hair loss"

Instead of asking [HRMED3] and [HRMED4], I was brought directly to [ACNE].

**Comment by cunnaneaq** [comment]
Update: The same thing happened when I selected [0] "Rogaine, Minoxidil, or Loniten" and/or [55] Other --> Was not asked [HRMED3] and [HRMED4], went straight to [ACNE]

**Comment by cusackjm** [comment]
issue was fixed when i tested 7/22 @ 3:05
