### ISSUE TITLE
Step 7 of e-consent: Indigenous Peoples (2 periods at the end of sentence two and space needed between words)

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/connectApp#150]
The end of the second sentence has 2 periods: "so our findings may benefit all communities.."  Please update this so that there is only 1 period.

**Comment by cunnaneaq** [comment]
Second screen on the Indigenous Peoples section of the e-consent, need a space between "for" and "return" in the last sentence "...we will work with the participant's family or other community members to determine a plan **forreturn** or destruction of their samples."

<img width="947" alt="Screen Shot 2021-07-22 at 5 20 38 PM" src="https://user-images.githubusercontent.com/83971268/126711056-bb93ece0-2347-48c3-ac53-09bb21220385.png">

**Comment by cusackjm** [comment]
confirmed changes made
