### ISSUE TITLE
[MHGROUP1] choice (8) HBP (Hypertension)

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/connectApp#152]
[SEX], I selected (1) Male
[MHGROUP1] 8: high blood pressure (hypertension)
I see the language "please do not include hypertension during pregnancy."

According to the Module 1 document, this is only supposed to appear if (0) female or (2) intersex is chosen.

**Comment by cunnaneaq** [comment]
When the pregnancy language is shown - when Sex=0 or Sex=2 - put brackets around the phrase [PLEASE DO NOT INCLUDE HYPERTENSION DURING PREGNANCY]

**Comment by cusackjm** [comment]
testing 7/28 indicates issue still exists

**Comment by anthonypetersen** [comment]
is this still an issue?

**Comment by cunnaneaq** [comment]
8/23/22 stage testing

Female CVD - 
@cusackjm do you think we need brackets around the pregnancy language for HBP answer choice?  If not, can close issue
![Screen Shot 2022-08-23 at 5 03 11 PM](https://user-images.githubusercontent.com/83971268/186265159-ede3612a-c72f-476a-baf1-40cf4e37909e.png)

Pregnancy text resolved for males in HBP
![Screen Shot 2022-08-23 at 5 04 39 PM](https://user-images.githubusercontent.com/83971268/186265395-94eac717-9aa4-4f28-b3ac-2194582afb4c.png)

**Comment by cusackjm** [comment]
no the [] were for fill instructions
