### ISSUE TITLE
"Contact" phone number at bottom banner is not listed

### ISSUE THREAD

**Issue by cusackjm** [episphere/connectApp#158]
![InkedScreen Shot 2021-07-02 at 1 14 35 PM_LI](https://user-images.githubusercontent.com/85582895/124972523-79022800-dff8-11eb-981d-93b43ddea85c.jpg)

**Comment by Davinkjohnson** [comment]
Do we still require the Phone number as a contact on the page?

**Comment by cunnaneaq** [comment]
Confirmed with Deanna that we don't want to list the phone number and the way it looks now (screenshot below) is correct.  I checked the links and they are working correctly.

![Screen Shot 2021-08-10 at 5 15 18 PM](https://user-images.githubusercontent.com/83971268/128936100-4d3e28a8-bebe-4dca-9197-ceba5d8b72c5.png)
