### ISSUE TITLE
Update Message Content: Consent to User Profile Transition Page

### ISSUE THREAD

**Issue by miagaudet** [episphere/connectApp#16]

**Comment by brotzmanmj** [comment]
Brian, please see this Invision link: https://publicis.invisionapp.com/share/UGZJO9N67R5#/screens/444734995 pages 9 and 10. Page 9 has the information that should appear on the Thank You screen after they submit their consent. Page 10 has the information for the screen that should appear after that. The 'Next' on page 10 should take them to the User Profile. Please remove the intro that is currently at the top of the user profile.

**Comment by miagaudet** [comment]
Please see GitHub Issues #27 for updated content.

**Comment by depietrodeanna** [comment]
On Thank You screen after submitting consent form and before My Profile, add this sentence at the end of the paragraph of text that starts with Thank you for interest in the Connect for Cancer Prevention Study: If you have any questions, please contact the Connect Support Center
