### ISSUE TITLE
respondents can select "I have not had any of these conditions" and specific conditions 

### ISSUE THREAD

**Issue by cusackjm** [episphere/connectApp#161]
Respondents can select "I have not had any of these conditions" and specific conditions for MHGROUP questions

Respondent should have the ability to only select either: 1 or more specific conditions, or only select the "I have not had any of these conditions" response

**Comment by cunnaneaq** [comment]
Please see the attached screenshot

![MyConnect Respiratory](https://user-images.githubusercontent.com/83971268/125343755-6f443180-e324-11eb-906b-206c6078d0df.jpeg)

**Comment by FrogGirl1123** [comment]
@cusackjm could you assign me and Brian to this project to make it easier for us to track?

I see the problem.  A code of 88 is required to trigger the locking of additional answers when "I have not had....." is selected.  But the 88 has been replaced by a concept ID for recording the response.  I will talk to Jen about it on the call today.

**Comment by cusackjm** [comment]
Just received similar issue from NORC: For Select All-type questions, "PREFER NOT TO ANSWER" is not exclusive; I can submit multiple responses along with "PREFER NOT TO ANSWER" (e.g., race question, ethnicity question)

**Comment by cusackjm** [comment]
testing 7/28 indicates issue resolved
