### ISSUE TITLE
Hyperlink the url on the "what else should i know" section of the "indigenous peoples" section in E-consent

### ISSUE THREAD

**Issue by cusackjm** [episphere/connectApp#162]
Inserting image...

**Comment by cusackjm** [comment]
![image](https://user-images.githubusercontent.com/85582895/125812944-81a32d18-288c-47ac-8e85-b1fcfeee7cdc.png)

**Comment by cunnaneaq** [comment]
In the first bullet in the screenshot above, "Reading more about participation and the details of what it means to take a part in Connect here"
Please hyperlink the word "here" with this website [https://www.cancer.gov/connect-prevention-study/what-to-expect]

**Comment by cusackjm** [comment]
![image](https://user-images.githubusercontent.com/85582895/128748530-f27a023a-e0bb-4b6c-9261-c0e0c01040f0.png)
 missing hyperlink now

**Comment by cusackjm** [comment]
ISSUE IS FIXED
