### ISSUE TITLE
Add progress bar 

### ISSUE THREAD

**Issue by cusackjm** [episphere/connectApp#165]
Include progress bar to improve navigation throughout the questionnaire

Per DCEG Feedback: 
"Would be nice to be able to click the progress bar to move across sections, rather than having to always click previous and back bottons" -Montse Garcia-Closas
"Should show a progress bar for the questionnaire " -Jennifer Loukissas

**Comment by anthonypetersen** [comment]
I believe Brian has implemented this?

**Comment by cusackjm** [comment]
@anthonypetersen progress bar implemented
