### ISSUE TITLE
Duplicate account message

### ISSUE THREAD

**Issue by depietrodeanna** [episphere/connectApp#173]
Add this message on dashboard when participant logs into a duplicate account. If possible, the participant will not be able to see the to-do list or click anything else. They should just view the message with no additional content on screen.

Message: _Our records show that there is another account linked to your sign in information. Please sign out of this account and sign in again using a different email address or phone number. If you cannot remember the information you used to create your account, please contact the Connect Support Center by emailing ConnectSupport@norc.org or calling 1-877-505-0253._

**Comment by cunnaneaq** [comment]
Confirmed with @depietrodeanna via email that the messaging Brian and I tested for a "Duplicate Account" is correct.

![Duplicate Account Message 5](https://user-images.githubusercontent.com/83971268/127923047-f9d28e6f-ee5e-4f83-81a0-888bd896b7a9.png)
is correct.
