### ISSUE TITLE
Skip pattern issue- ENDO2 not being shown

### ISSUE THREAD

**Issue by cusackjm** [episphere/connectApp#174]
Skip pattern issue- ENDO2 not being shown

"I did not receive the question [ENDO2] "Was your endometriosis confirmed with surgery?" (I only received the age at diagnosis question [ENDO])"

**Comment by cunnaneaq** [comment]
From NORC - able to replicate
[ENDO2] not asked

**Comment by cusackjm** [comment]
confirmed issue is resolved
