### ISSUE TITLE
Skip pattern issue: [BREASTSUR] went to [HYSTER], but should have gone to [BREASTSUR2]

### ISSUE THREAD

**Issue by cusackjm** [episphere/connectApp#175]
Skip pattern issue: [BREASTSUR] went to [HYSTER], but should have gone to [BREASTSUR2]

After selecting several answer choices at the question [BREASTSUR] "Which of these breast surgeries have you had? Please do not include a biopsy. Select all that apply." I was not routed to the question about my age at/year of surgery [BREASTSUR2]. Instead, I was routed to the age at/year of surgery for the hysterectomy item [HYSTER].

**Comment by cunnaneaq** [comment]
From NORC - I was able to re-create this issue
[BREASTSUR2] is skipped even if (6) Uterus removed (hysterectomy) is not selected
Jumps to the next surgical procedure selected

**Comment by cusackjm** [comment]
tested 7/28 issue still exists
