### ISSUE TITLE
Skip Pattern Issue: [OVARYREM] went to [FTREM], and not [OVARYREM2]

### ISSUE THREAD

**Issue by cusackjm** [episphere/connectApp#176]
Skip Pattern Issue: [OVARYREM] went to [FTREM], and not [OVARYREM2]

After selecting "I had surgery to remove one ovary" at the question [OVARYREM] "Which of these best describes the type of ovary removal surgery that you had?" I was not routed to the question about my age at/year of surgery [OVARYREM2]. Instead, I was routed to the question about the type of fallopian tube removal surgery [FTREM].

**Comment by cunnaneaq** [comment]
From NORC - I was able to replicate
[OVARYREM2] skipped

**Comment by cusackjm** [comment]
tested 7/28 issue still exists
