### ISSUE TITLE
[CHILDAGE] Issues- able to select multiple responses and enter age that doesn't make sense

### ISSUE THREAD

**Issue by cusackjm** [episphere/connectApp#179]
At [CHILDAGE], NORC was able to:
1. enter a child age greater than the Respondent's age 
2. enter an age (15) and select the "Less than 1 year old" option.

**Comment by cusackjm** [comment]
Example: See [Sheet](https://nih.app.box.com/services/box_for_office_online/4881/865805003586/91ea97.34ddb180b207c512a2acfa9121c197b9f4343fd44179b5f8218da209f037254a?node_type=file), Scenario 1 Tab: CHILDDEATH, CHILDAGE

**Comment by FrogGirl1123** [comment]
See issue #347 for Quest for the likely cause.

**Comment by cusackjm** [comment]
tested 10/1 still can enter child is 88 when participant is 52

**Comment by danielruss** [comment]
@Davinkjohnson  This is a separate issue.  Please assign to IMS, unless quest is failing.

**Comment by Davinkjohnson** [comment]
@danielruss @cusackjm Thanks both of you for looking into this. I'll pass this along to IMS.

**Comment by Davinkjohnson** [comment]
@cusackjm  is this still an issue or should I move it to the questionnaire repo for triage?

**Comment by cusackjm** [comment]
@Davinkjohnson this is resolved
