### ISSUE TITLE
Able to enter an age greater than my relative's current age or age at death for the cancer diagnosis questions

### ISSUE THREAD

**Issue by cusackjm** [episphere/connectApp#180]
Able to enter an age greater than my relative's current age or age at death for the cancer diagnosis questions

**Comment by cusackjm** [comment]
Example: see [Sheet](https://nih.app.box.com/services/box_for_office_online/4881/865805003586/91ea97.34ddb180b207c512a2acfa9121c197b9f4343fd44179b5f8218da209f037254a?node_type=file): , Scenario 1, DADCANC3H-J

**Comment by anthonypetersen** [comment]
is this still an issue?

**Comment by cusackjm** [comment]
this was fixed
