### ISSUE TITLE
Update Agreements Page 

### ISSUE THREAD

**Issue by miagaudet** [episphere/connectApp#19]
I believe this is complete but please verify.

Layout:
https://nih.app.box.com/file/766482088790?s=feqxv5q150mhsavewurw21zd197jzmfp

Comment on conditionality:
View and download signed consent and HIPAA authorization forms (hidden until consented), and (hidden but to be made available if requested) HIPAA revocation form

**Comment by brotzmanmj** [comment]
OCPL did not create comps for this as we said we would adapt what we have on other similar pages.

In addition to Consent and HIPAA form, we will have have two more forms to appear on the Agreements list only if triggered.
HIPAA Revocation Form - to appear on Agreements page only if the participant asks to revoke HIPAA authorization
Data Destruction Request Form - to appear on Agreements page only if participant requests data destruction
The triggers will come from data entered on the help desk agent dashboard.
Trigger for HIPAA revocation form to appear: HdWd_HIPAArevoked_v1r0 = 1
Trigger for data destruction form to appear: HdWd_Destroydata_v1r0 = 1

**Comment by brotzmanmj** [comment]
For the two new form names to appear on the agreements page, let's call them:
Revocation of Electronic Health Records Release (HIPAA Authorization) form
Data Destruction Request form

**Comment by brotzmanmj** [comment]
And here is the link to the Data Destruction Request Form: https://nih.app.box.com/file/791341048707?s=bh694xro30hv2d6r8mpkei28mnvvw1sm

**Comment by depietrodeanna** [comment]
For the Dashboard message that a user will see upon logging in, add this message/notification: "You have new forms to sign." 
And, link to the Agreements page on the word "forms."
