### ISSUE TITLE
Wrong skip pattern in Section 2 for participants that are SEX=01 male AND GEN=01 male

### ISSUE THREAD

**Issue by cusackjm** [episphere/connectApp#195]
Wrong skip pattern in Section 2 for participants that are SEX=01 male AND GEN=01 male. 

Right now they see Section 2 Reproductive health questions (starting at INTRONONCISWOM or INTROWH), but they should be skipped to TESTTHER.

**Comment by cunnaneaq** [comment]
11/18 - I tested as SEX=01 male and GEN=01 male; I did not see the reproductive health questions and was brought directly to TESTTHER
