### ISSUE TITLE
[Family History] Heading and [FAMHISTINTRO] Intro should be on same screen

### ISSUE THREAD

**Issue by cusackjm** [episphere/connectApp#199]
Family history header and text should be together. 

The Family History title and the text description are in two different screens, all the other sections have title and description in the same screen 
![image](https://user-images.githubusercontent.com/85582895/127032334-1e2d49a5-6c48-4f63-9fa1-0ebd75a15100.png)

**Comment by cunnaneaq** [comment]
On 10/1, I did not see the title "Family History". Instead it went straight from ACNE to the FAMHISTINTRO paragraph (Julie's second screen shot).

Ideally, this page would be consistent with the other intro pages for example: "Siblings," "Children," and "Education and Occupation" - screenshots below

![Screen Shot 2021-10-01 at 4 46 57 PM](https://user-images.githubusercontent.com/83971268/135684347-eac38d20-b67b-42b4-8a9e-da9fe77f6026.png)

![Screen Shot 2021-10-01 at 4 48 44 PM](https://user-images.githubusercontent.com/83971268/135684511-2f1c5dea-5c2d-4113-a5ff-028b18c2b79d.png)

![Screen Shot 2021-10-01 at 4 49 07 PM](https://user-images.githubusercontent.com/83971268/135684557-9716c5b1-a0ae-485e-8282-736b80a909ff.png)

**Comment by anthonypetersen** [comment]
is this still an issue?

**Comment by boyd-mj** [comment]
@cusackjm are you able to tell if this has been tested recently? I assume it would have come up in testing if it were still an issue and I know we've made fixes to headings.

**Comment by cunnaneaq** [comment]
"Family History" title and the intro paragraph are on the same screen in stage testing 8/23/22

![Screen Shot 2022-08-23 at 5 16 46 PM](https://user-images.githubusercontent.com/83971268/186267296-c4e2e335-1400-4828-8092-4ab4ecb1a00e.png)
