### ISSUE TITLE
Update Settings Page

### ISSUE THREAD

**Issue by miagaudet** [episphere/connectApp#20]
Layout (All of Us) and Content:
https://nih.app.box.com/file/766468206709?s=8mngryiu306q9lapm3j1msbggfytfvqm

Personal information: Not editable until verification; includes salutation, legal first name, last name, middle name, preferred first name, suffix

Contact information: mobile phone number, home phone number, other phone number, preferred email, additional email

Contact preferences: MVP: Email, notifications
B: SMS, call, WhatsApp - permission to leave voicemail/permission to text

Address: hidden until verification; home address (populate from module 4), mailing address (populate from user profile), secondary addresses (populate from Module 1) (add/ change option) 

Sign in: chosen log in (email address, mobile phone number); password (hashed variable; add/ change/ remove options), if they used non-gmail email and phone options; more input from Bhaumik

**Comment by cunnaneaq** [comment]
After verification, I was not able to edit my personal information in the My Profile tab (previously Settings).  From Mia's first comment, it seems like we would like participants to be able to edit this information once they have been verified.  Below please see the screenshots comparing my profile "Aileen Cunnane" to the example profile in the Comps from OCPL links above.  I did not have the edit buttons as shown in the example.

<img width="699" alt="Screen Shot 2021-06-23 at 3 26 53 PM" src="https://user-images.githubusercontent.com/83971268/123156562-723fb680-d437-11eb-90e1-e94d31b3a667.png">
<img width="714" alt="Screen Shot 2021-06-23 at 3 28 13 PM" src="https://user-images.githubusercontent.com/83971268/123156744-a4511880-d437-11eb-9115-902d0d526727.png">

**Comment by brotzmanmj** [comment]
Hi, We won't have the capability in place at launch for users to edit their user profile after verification. This is something we have on the list to work on enabling after launch. Thanks.

**Comment by cunnaneaq** [comment]
Thank you, Michelle.  I took off the label for this issue since it won't be worked on pre-launch.

**Comment by anthonypetersen** [comment]
Is there anything in this issue that we still want implemented?

**Comment by JoeArmani** [comment]
Closing - went into prod in the June release.
