### ISSUE TITLE
Remove "]" at beginning of sentence for SSN module

### ISSUE THREAD

**Issue by cusackjm** [episphere/connectApp#200]
![image](https://user-images.githubusercontent.com/85582895/127032551-cd6a8091-a1c9-4199-a450-6cc655fdc647.png)

**Comment by Leiloukou** [comment]
Can I contribute by doing this?
I am trying to get started with open source.

**Comment by anthonypetersen** [comment]
is this still an issue?

**Comment by cusackjm** [comment]
no this was fixed
