### ISSUE TITLE
E-consent typo in (3) Privacy: space between "your" and survey

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/connectApp#207]
On the third screen of the e-consent, there should be a space between the words "your" and "survey."  This is highlighted in yellow in the screenshot.

![Screen Shot 2021-07-26 at 4 35 36 PM](https://user-images.githubusercontent.com/83971268/127055451-797ac2e7-d273-471f-bb09-3aeaecc24b6d.png)

**Comment by cunnaneaq** [comment]
The image above was feedback from Chun, the PI at Sanford.  I am not seeing the same issue.  First screenshot is of my browser in my normal zoom, the second screenshot is my browser condensed so that "your" and "survey" are on the same line.  I am seeing the correct spacing.

![Screen Shot 2021-08-02 at 10 50 47 AM](https://user-images.githubusercontent.com/83971268/127914678-70f4d79b-34f2-4320-a292-af64f152edff.png)


![Screen Shot 2021-08-02 at 10 51 10 AM](https://user-images.githubusercontent.com/83971268/127914456-68383566-39d3-49eb-a01a-b4e33e8cbf97.png)

**Comment by cusackjm** [comment]
confirmed update made
