### ISSUE TITLE
Create the Notification Page

### ISSUE THREAD

**Issue by miagaudet** [episphere/connectApp#21]
Display (All of Us example):
https://nih.app.box.com/file/766478159673?s=8t59h5pah9rdhb735ir7312ocej18mt5

**Comment by brotzmanmj** [comment]
Comps from OCPL: 
Desktop: https://publicis.invisionapp.com/share/3710EWX3QP94#/screens/446868695?browse
Mobile: https://publicis.invisionapp.com/share/4E10F0TXHAVZ#/screens?browse

**Comment by brotzmanmj** [comment]
On notification (Messages) page, add the Subject line from the emails
