### ISSUE TITLE
[PREGSUMMARY] does not match answers from previous questions

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/connectApp#214]
[PREGSUMMARY] does not match what I entered in the previous questions. 
[PREG8] Did you breastfeed?  --> (1) YES 
[PREG9] How many months did you breastfeed? --> 15 
[PREGSUMMARY] 
Did you breastfeed: No 

![Screen Shot 2021-07-27 at 3 12 56 PM](https://user-images.githubusercontent.com/83971268/127213935-e6c0ab0c-5f77-4252-9f81-0ea93d643823.png)

**Comment by Davinkjohnson** [comment]
This should already be fixed

**Comment by cunnaneaq** [comment]
This is fixed.
