### ISSUE TITLE
[PROSREM] to [BLDTRANS] instead of [PROSREM2]

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/connectApp#223]
At [MHGROUP9] I selected (12) prostate removed (prostatectomy)
I was asked [PROSREM] "Which of these best describes the type of prostate removal surgery that you had?"
The next question should be [PROSREM2] "How old were you when you had all or part of your removed?...."
Instead I was brought directly to the next surgery selected or [BLDTRANS]

**Comment by cusackjm** [comment]
Issue appears resolved as of 9/29 testing

**Comment by cunnaneaq** [comment]
This issue was also resolved in my testing on 10/1
