### ISSUE TITLE
yellow message bar that appears on the home dshbrd is wrong during withdrawal/revocation/data destruction testing in dev

### ISSUE THREAD

**Issue by cusackjm** [episphere/connectApp#226]
After NORC and I tested the withdrawal/revocation/data destruction last week in dev, we noticed a few issues in the PWA for the participant I tested data destruction on (Connect ID: 6223902315). This was one of your test people that I borrowed. 

First, the yellow message bar that appears on the home dshbrd is wrong. It should be requesting them to sign two forms (data destruction and HIPAA revocation) and letting them know they have withdrawn from the study and have their data destroyed per their request. Instead it appears to be telling them they are ineligible. This did seem to display correctly for the withdrawn pt.

![image](https://user-images.githubusercontent.com/85582895/128767861-3b4314dc-b471-4b9e-9bae-31604b74430e.png)

**Comment by Davinkjohnson** [comment]
Brian is Investigating

**Comment by cusackjm** [comment]
issue is similar to https://github.com/episphere/connectApp/issues/230

**Comment by cunnaneaq** [comment]
This seems fixed.  This is the message that I see in the yellow bar for a withdrawn participant.  Data destruction and HIPAA revocation forms for this participant have been signed.

![Screen Shot 2021-08-19 at 5 17 24 PM](https://user-images.githubusercontent.com/83971268/130145445-81563ddc-90ec-4d6f-9070-243b56e8890e.png)

**Comment by cunnaneaq** [comment]
Ineligible messaging below.  Forms link is not there because the data destruction/HIPAA revocation forms have already been signed.

![Screen Shot 2021-08-23 at 2 07 03 PM](https://user-images.githubusercontent.com/83971268/130519943-89aadf1a-9850-4c88-aabd-3cd13a9ee8d1.png)
