### ISSUE TITLE
after I signed and submitted both forms the data destruction request still appeared under ‘forms to sign’. This should go away from here and just appear under ‘signed forms’ like revocation request did after it was signed.

### ISSUE THREAD

**Issue by cusackjm** [episphere/connectApp#227]
After NORC and I tested the withdrawal/revocation/data destruction last week in dev, we noticed a few issues in the PWA for the participant I tested data destruction on (Connect ID: 6223902315). This was one of your test people that I borrowed. 

after I signed and submitted both forms the data destruction request still appeared under ‘forms to sign’. This should go away from here and just appear under ‘signed forms’ like revocation request did after it was signed.

![image](https://user-images.githubusercontent.com/85582895/128768122-00be9f9f-c52e-41c7-a250-98373d118f0e.png)

**Comment by cunnaneaq** [comment]
Forms section still looks like this.  The signed data destruction form is still appearing under "forms to sign"

![Screen Shot 2021-08-10 at 4 08 04 PM](https://user-images.githubusercontent.com/83971268/128927961-582d5612-0911-4d9a-815a-eed75ee9341b.png)
