### ISSUE TITLE
Outreach Timed Out Messaging 

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/connectApp#230]
Core Message: 

"Our study team has been trying to contact you about your eligibility for the Connect for Cancer Prevention Study. We need more information from you to check that you can be part of Connect. Please contact [IHCS contact info] or [the Connect Support Center by emailing ConnectSupport@norc.org or calling 1-877-505-0253 or] to confirm that you can take part in the study."

7/9 sites want to use their individual site's information in the part that says [IHCS contact info].  CSC contact will not be included for these sites.

Marshfield (definitely) and University of Chicago (most likely) want to use CSC for the contact information and not supply their individual site's contact.

Last time we checked the Outreach Timed Out messaging it was incorrect and looked like the screenshot below.

![Outreach Timed Out Message 64](https://user-images.githubusercontent.com/83971268/129274207-a3ac38df-cd2f-4541-a8e8-1ac54db9a987.png)

**Comment by cusackjm** [comment]
Issue is similar to https://github.com/episphere/connectApp/issues/226

**Comment by cunnaneaq** [comment]
Need to provide Brian with the contact information for the 7 sites that wanted to be contacted instead of CSC

**Comment by cunnaneaq** [comment]
Core message in PWA looks good (screenshot below).  Please use the following contact information for each site:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/cunnaneaq/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/cunnaneaq/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">



</head>

<body link="#0563C1" vlink="#954F72">



Site: | Please Contact:
-- | --
Health Partners | HealthPartners by emailing ConnectStudy@healthpartners.com or calling   952-967-5067
Henry Ford | Henry Ford Health System by emailing ConnectStudy@hfhs.org
Marshfield | the Connect Support Center by emailing ConnectSupport@norc.org or calling   1-877-505-0253
KPCO | KP Colorado by emailing Connect-Study-KPCO@kp.org or calling 303-636-3126
KPGA | KP Georgia by emailing Connect-Study-KPGA@kp.org or calling 404-745-5115
KPNW | KP Northwest by emailing Connect-Study-KPNW@kp.org or calling   1-866-554-6039 (tollfree) or 503-528-3985
KPHI | KP Hawaii by emailing Connect-Study-KPHI@kp.org or calling 833-417-0846
Sanford Health | Sanford Health by emailing ConnectStudy@sanfordhealth.org or calling   605-312-6100
UChicago | the Connect Support Center by emailing ConnectSupport@norc.org or calling   1-877-505-0253



</body>

</html>


![Screen Shot 2021-08-23 at 2 06 08 PM](https://user-images.githubusercontent.com/83971268/130636931-b2dabc0a-c2e5-4d9c-a4e1-1c395984512f.png)

**Comment by cunnaneaq** [comment]
Checked each sites' messaging with Brian 9/24/21.  All look good!  Screenshots available if needed.
