### ISSUE TITLE
Fix Enrollment Status variable derivation

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/connectApp#236]
The Enrollment Status variable isn't being derived accurately, per Marshfield testing in dev. 

Connect IDs and what the enrollment status should be vs what it actually is are in an email from Marshfield forwarded to Brian and Madhuri from Michelle on 9/9/21.  Also in Box: https://app.box.com/file/846099407725 (see column N)

Also, the Master Data Dictionary needs clearer definition for this variable

**Comment by FrogGirl1123** [comment]
@brotzmanmj @mnataraj92 and I met today to discuss.  We decided to delete the Enrollment Status variable from Dev and from the Master Data Dictionary.  We will derive a new variable once the biospecimens are in place.

@cunnaneaq could you post an issue for @abhinavjonnada82 to remove the Enrollment Status, concept ID 507120821 for the Dev tier study manager dashboards?

@mnataraj92 would you please delete the Enrollment status variable from the Master Data Dictionary?
