### ISSUE TITLE
Edit content on My Samples page

### ISSUE THREAD

**Issue by depietrodeanna** [episphere/connectApp#237]
Please change the current wording on the My Samples page to the below:

New wording:
We will begin collecting samples early in 2022. We will reach out to you with instructions and next steps when it is time to donate samples. Thank you for being part of Connect!

**Comment by cunnaneaq** [comment]
Looks good!

![image0](https://user-images.githubusercontent.com/83971268/134722085-bdf94ac8-e2bb-4190-8909-6f0b4fba6bb5.png)
