### ISSUE TITLE
FOR REFERENCE: Style Guide Requirements

### ISSUE THREAD

**Issue by miagaudet** [episphere/connectApp#24]
Style Guide:
https://nih.app.box.com/file/742356999668?s=rj7gq69m4bc4ncdu2h2ccvm57ly6khmh

Test site for the public-facing website (note you need to be in VPN):
https://ncigovcdode408.prod.acquia-sites.com/connect-prevention-study/dceg-connect

**Comment by anthonypetersen** [comment]
Not needed as an issue anymore
