### ISSUE TITLE
Skip pattern failure when selecting multiple responses AND "Other please describe"

### ISSUE THREAD

**Issue by cusackjm** [episphere/connectApp#240]
It seems that skip patterns don't happen when multiple responses are selected and the open-ended "other please describe" is selected and completed.

EXAMPLE 1:
Reported 2 siblings. For the 1st sibling I selected 10,11,12,77 (Other please describe) "liver" at SIBCANC2 but was not looped through SINBCANC3 age of diagnosis questions. For the 2nd sibling I was correctly looped through the age of diagnosis questions (and I did not select other please describe)

**Comment by cusackjm** [comment]
Also occurred at RACEETH when I selected 1, 3, 5, and 55 "none of these fully describe me: please describe": "pokemon". I was not taken to RACEETH3, RACEETH5, or RACEETH7. Instead I was taken to LANG.

**Comment by FrogGirl1123** [comment]
This issue still occurs even when reverting back to the [text box:VARNAME].  The issue seems to be that the other choices are not stored on the backend if 55 is selected and the text box is populated.  If you select 55 without populating the text box the skip patterns work.

**Comment by danielruss** [comment]
Found Bug related to fix for bug  https://github.com/episphere/quest/issues/341

**Comment by FrogGirl1123** [comment]
Thanks, @danielruss.  Are changes needed to the markup or should it work as is with this fix?

**Comment by cusackjm** [comment]
Issue still exists for RACEETH, BREASTSUR, MOMCANC2, DADCANC2. I tested selecting conditions and the "please describe" open ended response, and selecting the "please describe" open ended response on it's own.

**Comment by danielruss** [comment]
@cusackjm   Made another fix.  Please test RACEETH.   Will look at BREASTSUR  next to make sure it is the same issue.

**Comment by danielruss** [comment]
BREASTSUR appears to work.

**Comment by danielruss** [comment]
@cusackjm have you had a chance to look at the fix?

**Comment by cusackjm** [comment]
RACEETH appears to work
