### ISSUE TITLE
Message with Login link goes to "promotions" tab for Gmail accounts

### ISSUE THREAD

**Issue by cusackjm** [episphere/connectApp#242]
When logging in with the link sent to the participant's email, in Gmail, the message goes to the "promotions" tab (which is typically ads from companies). Before we used this method, Connect emails ended up in the "primary" tab. 

Might be an issue in future because promotional emails do not notify the account holder of a new message (unless the account holder changes the notifications), and if participants don't check the "promotions" tab, they may think that the email was not sent.  (In my personal experience I get hundreds of promotional emails every day that I don't look through).

![image](https://user-images.githubusercontent.com/85582895/135470401-f65acd86-7bae-48a1-a801-a82b6a41db01.png)

**Comment by Davinkjohnson** [comment]
We looked into this fairly extensively and are not able to change this behavior. (Also believe this issue is a duplicate)
