### ISSUE TITLE
HRMED skip pattern not showing HRMED3 & HRMED4, when selecting 0/1 at HRMED2 

### ISSUE THREAD

**Issue by cusackjm** [episphere/connectApp#243]
HRMED skip pattern not showing HRMED3 & HRMED4, when selecting 0/1 at HRMED2  

In a scenario with a participant that's SEX=2, I did not see HAIRFEM/HAIRMALE and saw HRMED (both are correct). I then selected 1  at HRMED, 0 and 1 at HRMED2, but was not taken to HRMED3 or HRMED4. Instead I was taken to ACNE. 

Issue also exists when SEX=0 and GEN=0

**Comment by FrogGirl1123** [comment]
From what we cold tell testing with IMS in the Quest App yesterday the issue seemed to be related to the unrestricted < -> ACNE > at the end of the HRMED question.  When the < -> ACNE > is removed or replaced with < #NR -> ACNE > the skip pattern seems to work correctly.  

@danialruss is this how it's supposed to work?
@Davinkjohnson  could you please tag Daniel and Iqbal

[HRMED?] Have you ever used medication to treat <b>thinning hair or hair loss</b>?
(1) Yes -> HRMED2
(0) No
< #NR -> ACNE >

[HRMED2?] What medication did you use to treat thinning hair or hair loss? Select all that apply.
[0] Rogaine®, Minoxidil, or Loniten®
[1,displayif=or(equals(SEX,1),equals(SEX,2))]Finasteride
[55] Other: Please describe |__|id=HRMED2_TB|

[HRMED3?] How old were you when you <b>first</b> used medication to treat thinning hair or hair loss?
|__|__|min=0 max=isDefined(AGE,age)| Age

[HRMED4?] How old were you when you <b>last</b> used medication to treat thinning hair or hair loss? If you are currently using medication to treat thinning hair or hair loss, enter your current age.
|__|__|min=0 max=isDefined(AGE,age)| Age

[ACNE?] <b>Acne</b>

Have you ever seen a doctor or other health professional for <b>severe or ongoing acne</b>?
(1) Yes -> ACNE2
(0) No -> FAMHISTINTRO
< #NR -> FAMHISTINTRO >

**Comment by danielruss** [comment]
```
[HRMED?] Have you ever used medication to treat thinning hair or hair loss? (1) Yes -> HRMED2 (0) No < #NR -> ACNE >
```


If the user selects:
Yes:  Go to HRMED2 
No:   Go to the next question (In this case HRMED2)
No Response go to ACNE


If the question was:
```
[HRMED?] Have you ever used medication to treat thinning hair or hair loss? 
(1) Yes -> HRMED2 
(0) No 
<  -> ACNE >
```

If the user selects:
Yes:  Go to HRMED2 THEN ACNE
No:   ACNE
No Response go to ACNE

**Comment by danielruss** [comment]
I think the logic you want is:

```
[HRMED?] Have you ever used medication to treat thinning hair or hair loss?
(1) Yes 
(0) No -> ACNE
< #NR -> ACNE >
```
Why?  
If the user selects:
Yes: Go to the next question (In this case HRMED2)
No: Go to ACNE
No Response: Go to ACNE

**Comment by danielruss** [comment]
Rule of Thumb:

When the next question is the question that follows in the markdown dont use ->.  It is the default.

When you want to SKIP to a question because the user did not respond user < #NR -> >

When you can want to ask questions based on multiple responses (Think RACEETH) 
```a -> FOLLOW_UP_A
b -> FOLLOW_UP_B
c -> FOLLOW_UP_C
< -> NEXT_QUESTION >.
If a user select a and B the follow questions will be asked: FOLLOW_UP_A, FOLLOW_UP_B, NEXT_QUESTION

What if the user does not make a response?  It goes to NEXT_QUESTION

What if I want the user to see a no response follow up queston?  Then add 
< #NR -> FOLOWUP_NO_RESPONSE >

**Comment by FrogGirl1123** [comment]
@danielruss Thank you for the detailed explanation.  I will share it with IMS.

@naiyume could you please make the change Daniel suggested to the transformed version of the markup in the Dev PWA.  It would be good if @cusackjm could test it before we move Module 1 into stage for testing on Monday.

**Comment by cunnaneaq** [comment]
Tested 10/4 - saw HRMED3 and HRMED4 when HRMED=1 ("yes") and any combination of medications was selected at HRMED2.  This was true for SEX=0 GEN=0, SEX=1 GEN=1, and SEX=2 GEN=4

**Comment by danielruss** [comment]
@cunnaneaq  please close the bug is resolved.

**Comment by cusackjm** [comment]
Issue was not fixed in Stage
