### ISSUE TITLE
remove enrollment status from dev

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/connectApp#244]
@abhinavjonnada82 can you please remove the Enrollment Status, concept ID 507120821 for the Dev tier study manager dashboards?

Please see issue #236 for additional information.

**Comment by anthonypetersen** [comment]
@cunnaneaq is this still an issue?

**Comment by cunnaneaq** [comment]
@abhinavjonnada82 confirmed this is resolved - concept ID removed from dev
