### ISSUE TITLE
"Cancer" not included following [text entry] for MOMCANC3V, DADCANC3U, SIBCANC3X, CHILDCANC3X

### ISSUE THREAD

**Issue by cusackjm** [episphere/connectApp#247]
For all of the age of dx questions for 55 "text" responses (MOMCANC3V, DADCANC3U, SIBCANC3X, CHILDCANC3X), "cancer" was not included in the question, following the [text entry] entered with the 55 response

For example, "How old was emily when they were first told by a doctor or other health professional that they have or had **leg**"? (should be "**leg cancer**")

**Comment by anthonypetersen** [comment]
is this still an issue?

**Comment by cusackjm** [comment]
no this was fixed
