### ISSUE TITLE
Survey Glitch when submitting - missing data

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/connectApp#252]
After I clicked submit for Module 1, I was brought back to the log-in screen instead of the MyConnect Dashboard.  When I logged back in, Module 1 wasn't submitted (the START button was still purple).  When I clicked on START I was brought to the end of the module, and clicked submit again.  Then, I was brought to the Dashboard and saw the date/time stamp.

When Nicole reviewed the back-end data of the account where this occurred, she noticed that some of the data entered at the end of the module was missing (e.g., PPLHOUSE, ALTADDRESS1&2, ALTCONTACT1&2, QXAUTHOR1).

**Comment by anthonypetersen** [comment]
is this still an issue?
