### ISSUE TITLE
On Hold: Samples- Draft content for instructions on how to give samples

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/connectApp#26]
Very early draft of the content for how to give baseline samples is here: https://nih.app.box.com/file/775308070169?s=2n3m3jn2eqdksh7x1p4bdxr7f85kmp6g 

Purpose is not to load this content yet but to think about the size and scope of content and where it belongs in the information architecture on the app.

**Comment by brotzmanmj** [comment]
Will discuss placement with OCPL before adding to PWA, and what content should appear at launch

**Comment by anthonypetersen** [comment]
@depietrodeanna feels like this can be closed?
