### ISSUE TITLE
Update message content that appears after submit User Profile

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/connectApp#27]
If they had a valid token or PIN, display this message on their dashboard after they submit the user profile:

Thank you for completing your profile for the Connect for Cancer Prevention Study. Next, the Connect team at your health care system will check that you are eligible to be part of the study. We will contact you within a few business days.  

In the meantime, please begin by completing your first Connect survey. The survey is split into four sections. You can pause and return to complete these sections at any time. 

Questions? Please contact the Connect Support Center. (hyperlink to the Help Desk web form) 

If they did not have a valid token or PIN: 

Display this message content after they submit they user profile

Thank you for completing your profile for the Connect for Cancer Prevention Study. Next, the Connect team at your health care system will check that you are eligible to be part of the study. We will contact you within a few business days to share information about next steps.  

Questions? Please contact the Connect Support Center. (hyperlink to the Help Desk web form).

**Comment by brotzmanmj** [comment]
@naiyume Hi Brian, we updated the messages that should appear after submitting the user profile and we added what the second message should be if they log in again and are still unverified. The change are in the Enrollment Trajectories document, page 3 in the table titled ' Pre-Verification https://nih.app.box.com/file/777855862652?s=n0biiy75k1eew5j5pyjnrmhhxgsktoin

**Comment by depietrodeanna** [comment]
For user that has a valid token/PIN, This text needs to be added to the end of the message that appears on the "thank you" screen after submitting the user profile: 

In the meantime, please begin by completing your first Connect survey.
