### ISSUE TITLE
Add language to main sign in page - push to stage

### ISSUE THREAD

**Issue by depietrodeanna** [episphere/connectApp#276]
Please add the below language above the disclaimer language about the Connect logo trademark on the main PWA sign in page. This language should come before the disclaimer language but after the sign in with email and sign in with phone buttons:

**If you are a Connect participant, please sign in with the email or phone number you used to sign up for the study.**

**Comment by Davinkjohnson** [comment]
@anthonypetersen please work with @naiyume on this as an opportunity to start learning the PWA.

**Comment by anthonypetersen** [comment]
pushed to dev

**Comment by depietrodeanna** [comment]
@anthonypetersen Can you change the text to: "If you have an account, please sign in with the email or phone number you used to create your account." please?

**Comment by anthonypetersen** [comment]
in prod
