### ISSUE TITLE
Update e-consent signature section and indigenous peoples section

### ISSUE THREAD

**Issue by robertsamm** [episphere/connectApp#277]
Please update the educational modules (e-consent screens) in the PWA for the changes below
1. Indigenous People's screen - these screens need to be updated to reorder the information. Please see the tracked changes in the file attached for this change. (pgs 4-6)
2. electronic signature section - please update this section to include added language that makes clear that typing their name will sign the form. (note: this change should be two sentences, please also include a period between "form" and "These", it is currently missing from the file)

Note: the tracked changes on the privacy screen you can ignore, this was just to align the file with what we already have in the PWA.

[000034_Connect_EducationalScreens_V1.2_11182021_Tracked.docx](https://github.com/episphere/connectApp/files/7636338/000034_Connect_EducationalScreens_V1.2_11182021_Tracked.docx)

**Comment by anthonypetersen** [comment]
@robertsamm is this still needed?

**Comment by robertsamm** [comment]
No, closing
