### ISSUE TITLE
MyConnect navigation issue in Firefox

### ISSUE THREAD

**Issue by Davinkjohnson** [episphere/connectApp#279]
In Firefox, once http://myconnect.cancer.gov/ page loads (from clicking the microsite Join Now button) the browser back button does not work as expected to navigate back to http://www.cancer.gov/connect-prevention-study.

**Comment by anthonypetersen** [comment]
@Davinkjohnson just tested and working as expected (I think) can you confirm?

**Comment by Davinkjohnson** [comment]
Yup this works in Prod. Bhaumik fixed it a while ago and I forgot to close the issue. (Glad to see it still works)
