### ISSUE TITLE
Update message content that appears after verification 

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/connectApp#28]
Message content after verification will differ depending on verification status as follows:

If 'Verified' Display this message content: 

Great news! We have confirmed that you are eligible for the Connect for Cancer Prevention Study. You are now an official Connect participant.  

[if any of four survey sections have not been completed]:  

The next step is to complete your Connect survey. The survey is split into four sections. You can pause and return to complete these sections at any time. 

[if all four survey sections have been completed]: Thank you for completing your Connect surveys! We will be in touch with next steps. Thank you for being a part of Connect and for your commitment to help us learn how to prevent cancer. 

Questions? Please contact the Connect Support Center [MyConnect.cancer.gov/support] 

If 'Cannot Be Verified', display this message:

Our records show that you are not eligible for the Connect for Cancer Prevention Study. Thank you for your interest. If you think this is an error or if you have any questions, please contact the Connect Support Center. [MyConnect.cancer.gov/support] 

Any information that you have already provided will remain private. We will not use any information you shared for our research. 

If 'Duplicate': No message should appear. We are assuming records marked as Duplicates are not accounts that real people have used so need no messaging. We should test this in end to end testing with sites to confirm.

If 'Outreach Timed Out' This message will be specific to each site:

We need more information from you in order to check that you can be part of the Connect for Cancer Prevention Study. Please contact [site specific information] to confirm your eligibility for Connect. 

If Outreach time out is changed to Verified or Cannot be Verified, display the relevant message and dashboard items for those statuses above.

**Comment by naiyume** [comment]
Should these appear in the warning section that we currently have in the todo list?
Also, do we have a message fr unverified but used a pin, r are we going with what I have in there for now

**Comment by brotzmanmj** [comment]
Yes, these messages should appear in the yellow box above the To Do list. For the messages if they are not yet verified, see issue #27

**Comment by brotzmanmj** [comment]
@naiyume We updated the content of these messages that appear after verification and also added a second message that should appear if they log in again. It wasn't possible to edit in a clear way within this github issues, so please refer to the Enrollment Trajectories document on Box: https://nih.app.box.com/file/777855862652?s=n0biiy75k1eew5j5pyjnrmhhxgsktoin 
on page 4 half way down (see the table titled 'After Verification'

**Comment by depietrodeanna** [comment]
For verified, the current text needs to be edited to say this message: Great news! We have confirmed that you are eligible for the Connect for Cancer Prevention Study. You are now an official Connect participant.
The next step is to complete your first Connect survey. Questions? Please contact the Connect Support Center [MyConnect.cancer.gov/support]

**Comment by depietrodeanna** [comment]
Messages need to be updated for verified people who log back into the app again and have not yet completed their surveys. Please refer to this document that contains the text for various conditions:  https://nih.app.box.com/file/777855862652?s=n0biiy75k1eew5j5pyjnrmhhxgsktoin

**Comment by depietrodeanna** [comment]
For people who have completed all four sections of the first survey, the message that appears needs to be edited "Thank you for completing your first Connect surveys! We will be in touch with next steps." "surveys" needs to be changed to "survey"
