### ISSUE TITLE
Remove message in yellow notification bar that refers to completing first survey

### ISSUE THREAD

**Issue by depietrodeanna** [episphere/connectApp#280]
Remove the message that participants see on the dashboard any time they log into the PWA before they submit all four modules of the first survey. The message as stated is causing confusion because currently not all four modules are available. So even if someone submits module 1, they will still see the message. After someone submits module 1, the message should no longer be displayed. Please remove entire message- "Please complete your first Connect survey. Thank you for being a part of Connect."

**Comment by cunnaneaq** [comment]
Done - yellow bar message removed for participants who have completed module 1

![Screen Shot 2021-12-16 at 9 30 09 AM](https://user-images.githubusercontent.com/83971268/146390572-0a818acd-c9f0-407a-b60b-b25f694274f9.png)
