### ISSUE TITLE
SSN Survey Submission Updates

### ISSUE THREAD

**Issue by Davinkjohnson** [episphere/connectApp#281]
Background) Edit the line, “Thank you for completing this section of the questionnaire.” If possible. We should refer to the SSN module as “survey,” since that is the term we use to refer to all quex content (not “modules,” “questionnaires,” etc.). Also remove, “section of” text

1) Language is distinct between mod 1 and SSN implying we can make edits on these screens that are unique to each survey, correct?

2) My suggestion for SSN: “Thank you for completing this survey. Please click “Submit Survey” below to continue.”
3) can we edit any of the other language? For example, the content in the “Submit Answers” confirmation box?

first page
![image](https://user-images.githubusercontent.com/87718852/145490135-0b2eebce-c44b-4aa9-8ff3-f4111997c088.png)
second Modal
![image](https://user-images.githubusercontent.com/87718852/145489989-2668bd93-5da0-429b-996b-d37bf6aac9ae.png)

**Comment by anthonypetersen** [comment]
@Davinkjohnson is this still an issue?

**Comment by Davinkjohnson** [comment]
Not sure... I know we just updated the messaging for the last message of the surveys and that we'll be re-doing the yellow bar messages again.

**Comment by anthonypetersen** [comment]
(1 / 2) It looks like the version of the SSN module that IMS pushed has the language changes you want, it's just not in production yet.


(3) That language can be modified for that modal, but the code lives inside Quest not the PWA.

**Comment by anthonypetersen** [comment]
closing
