### ISSUE TITLE
Responses for HdRef_Basesrv_v1r0 Not Populating Correctly

### ISSUE THREAD

**Issue by mnataraj92** [episphere/connectApp#282]
"Yes" is not being stored in the same format as the "no" for 994064239 (HdRef_Basesrv_v1r0). Note that "no" is set as the default. 

Mentioning @FrogGirl1123 since I will be out next week. Thanks!

**Comment by brotzmanmj** [comment]
@mnataraj92 @abhinavjonnada82 @FrogGirl1123 Checking on this one as it is relevant to the refusal/withdrawal updates and retesting. Has this been resolved?

**Comment by anthonypetersen** [comment]
is this still an issue? @mnataraj92 @abhinavjonnada82 @FrogGirl1123

**Comment by mnataraj92** [comment]
i think this has been resolved
