### ISSUE TITLE
Format for Date of Consent

### ISSUE THREAD

**Issue by FrogGirl1123** [episphere/connectApp#285]
The date for consent, CID 982402227, is being saved as yyyyddmm instead of as described in the data dictionary which is yyyymmdd.  Could this format be made to match the Master Data Dictionary?

**Comment by don-martin** [comment]
Can I get an update on this please?  It's holding up our testing.  Thanks.

**Comment by anthonypetersen** [comment]
@don-martin found the bug in our code base, working on a fix

**Comment by Davinkjohnson** [comment]
related to https://github.com/episphere/dashboard/issues/267

**Comment by FrogGirl1123** [comment]
We made the decision to deprecate CID 982402227 since it is not being used. The column will remain in prod, but it's not in use. The decision was made on 1/11/2022 in the Prep meeting.
