### ISSUE TITLE
Site-specific My Samples page content

### ISSUE THREAD

**Issue by depietrodeanna** [episphere/connectApp#291]
Configure My Samples page with content for the five sites for which content is linked below. Please note that once these are mocked up in dev, we’ll need to review internally and also share the final drafts with the sites so they can confirm that all information is accurate.
 
HealthPartners: https://nih.box.com/s/5f96oni440zklaxt20i4qxg4fvqfuwim
Sanford: https://nih.box.com/s/e5xonzmm27rvd77crt1mnrbalit51a7v
Marshfield: https://nih.box.com/s/6wwbw9bkvevmpk0v9d053h8mokb7jm0d
Henry Ford: https://nih.box.com/s/ppp1rp3ooljceidv17lao3n0tpw9dpom
UChicago: https://nih.box.com/s/mkipmbpsdz36hgrjuk8iev564gkpr2v0
 
For each of the KPs, implement a message placeholder on the My Samples page until further notice. Language here:
**We will begin collecting samples later this year. We will send you an email with instructions and next steps when it is time to donate samples. Thank you for being part of Connect!**

**Comment by cunnaneaq** [comment]
I reviewed the MySamples page in the PWA for each of the sites and compared it to the documents linked above.  I noted discrepancies in this spreadsheet (https://nih.app.box.com/file/924697739563).  Please let me know if you have any questions

**Comment by depietrodeanna** [comment]
@anthonypetersen the My Samples templates now contain additional scheduling considerations under the "When Should I Donate My Samples" heading for the research sites. Please update as you make the changes noted in Aileens spreadsheet.

**Comment by cunnaneaq** [comment]
Changes from 2-28 look good!  Additional changes made in 3-7-22 tab in spreadsheet (https://nih.app.box.com/file/924697739563) This includes the changes Deanna noted in the comment above.

**Comment by cunnaneaq** [comment]
Changes made and checked in dev.  Changes pushed to stage - working on testing in stage ASAP.

**Comment by anthonypetersen** [comment]
@cunnaneaq @depietrodeanna can this be closed?

**Comment by depietrodeanna** [comment]
Hi- we have some minor edits that we're gathering from the sites after they took a pass at these in Stage. I am compiling in a spreadsheet and will add here in the next day or so. @anthonypetersen @cunnaneaq

**Comment by anthonypetersen** [comment]
content changes pushed to dev

**Comment by depietrodeanna** [comment]
Hyperlink CSC contact info MyConnect.cancer.gov/support and the CSC email (ConnectSupport@norc.org) on all My Samples pages.

**Comment by anthonypetersen** [comment]
@depietrodeanna @cunnaneaq let me know if this looks good in dev and we can move to stage

**Comment by depietrodeanna** [comment]
@anthonypetersen HP has a last minute timing adjustment- please edit the Monday-Thursday hours, they should end at **3:00 p.m.** instead of 3:30 p.m. 

This is what it should look like:

**Hours** 
Monday - Thursday: 7:30 a.m.-3:00 p.m.
Friday: 7:30 a.m.- 1:30 p.m.

**Comment by cunnaneaq** [comment]
Sanford looks good in dev!

![Screen Shot 2022-06-06 at 12 38 10 PM](https://user-images.githubusercontent.com/83971268/172205365-afeae4a7-f250-4246-a482-8fcfa0914eae.png)

**Comment by cunnaneaq** [comment]
HP time change also looks good in dev!  @depietrodeanna @anthonypetersen push to stage?

![Screen Shot 2022-06-06 at 2 21 17 PM](https://user-images.githubusercontent.com/83971268/172222025-a824da2a-efc4-46e9-8fb0-3c4532a373f4.png)

**Comment by anthonypetersen** [comment]
@depietrodeanna @cunnaneaq I'm good with that if everyone else is

**Comment by depietrodeanna** [comment]
@anthonypetersen @cunnaneaq make it so :)

**Comment by cunnaneaq** [comment]
changes look good in stage.  Tony pushed to prod!
