### ISSUE TITLE
Updates to Payment Round Variables

### ISSUE THREAD

**Issue by FrogGirl1123** [episphere/connectApp#293]
This issue is to track 2 outstanding issues on the Payment Round variables in the participants table.
1) The data structure for Payment needs to be updated to:

130371375: {​​​
266600170: {​​​ // Baseline
731498909:104430631,
648936790:104430631,
648228701:104430631,
222373868:104430631
}​​​,
496823485: {​​​ // Follow up 1
731498909:104430631,
648936790:104430631,
648228701:104430631,
222373868:104430631
}​​​,
650465111: {​​​ // Follow up 2
731498909:104430631,
648936790:104430631,
648228701:104430631,
222373868:104430631
}​​​,
303552867: {​​​ // Follow up 3
731498909:104430631,
648936790:104430631,
648228701:104430631,
222373868:104430631
}​​​
}​​​

in the dev, stage and prod environments for new data.

2) The default data already in prod for the "floating" structure needs to be corrected to the above.

**Comment by anthonypetersen** [comment]
is this still an issue?

**Comment by anthonypetersen** [comment]
Bhaumik implemented prior to leaving
