### ISSUE TITLE
Combined Biospecimen Survey Status Variable

### ISSUE THREAD

**Issue by FrogGirl1123** [episphere/connectApp#294]
Related to issue #292 

A survey status variable (not started, started, submitted) for the combined version of the Biospecimen Survey (Blood, Urine, and Mouthwash) needs to be added to the master dictionary.

**Comment by brotzmanmj** [comment]
Also add two time stamp variables for this survey: Date/time started and Date/time submitted

**Comment by mnataraj92** [comment]
This has been added (265193023) along w/the timestamps
