### ISSUE TITLE
Create status variable for SSN Survey

### ISSUE THREAD

**Issue by FrogGirl1123** [episphere/connectApp#295]
Create a not started, started, submitted status variable for the SSN Survey in the master data dictionary

**Comment by brotzmanmj** [comment]
@FrogGirl1123 @mnataraj92  Also create variables for date/time started and date/time submitted SSN survey.
And should we elevate the priority to be included in the upcoming run of the data dictionary? The variables will be needed for the biospecimen dashboard.

**Comment by mnataraj92** [comment]
This has been created (126331570) along w/the time stamps
