### ISSUE TITLE
Add Check-out time stamp variable

### ISSUE THREAD

**Issue by FrogGirl1123** [episphere/connectApp#296]
Add a variable for the biospecimen check-out time stamp to to the Master Data Dictionary, currently there is only a check-in time stamp.  Please include in the notes for both the check-in and check-out time stamps that these are set during the first check-in and are NOT to be written over during and subsequent check-ins.

**Comment by anthonypetersen** [comment]
@FrogGirl1123 @brotzmanmj Should this issue be on the Biospecimen board / project and not the Connect PWA project?

**Comment by brotzmanmj** [comment]
@Davinkjohnson @FrogGirl1123 @anthonypetersen I think Davin was planning to look through these issues Nicole added last week and move them to whichever project board was most relevant

**Comment by anthonypetersen** [comment]
@brotzmanmj can this be closed on this board?

**Comment by brotzmanmj** [comment]
@anthonypetersen I think this board is where we're tracking needs for DD changes

**Comment by anthonypetersen** [comment]
@brotzmanmj I thought this board was for the PWA? Either way I believe we've added this concept ID already? (343048998)

**Comment by anthonypetersen** [comment]
@mnataraj92 can you confirm?

**Comment by mnataraj92** [comment]
This variable has been renamed to BioFin_CheckOutTime_v1r0 in the master dictionary (concept ID 343048998)

**Comment by Davinkjohnson** [comment]
@mnataraj92 can this issue be closed? (Tony confirmed this is being used in our code and in the MasterComb DD) @FrogGirl1123

**Comment by Davinkjohnson** [comment]
@FrogGirl1123 @brotzmanmj I believe this is working as desired in Prod, correct?
