### ISSUE TITLE
BPTL Dashboard Concept IDs - Possible Updates Required

### ISSUE THREAD

**Issue by FrogGirl1123** [episphere/connectApp#299]
The concept IDs for the BPTL dashboard were created in Oct. 2021 but not added to the Master Data Dictionary until 1/18/22.  Because of the lag in the update, these concept IDs may not longer be correct relative to the "gold standard" file.  Checks of the concept IDs are in progress.  While the current concept IDs can be used for programming and upcoming testing, it should be noted that these might change and need to be updated in the code.

**Comment by anthonypetersen** [comment]
is this still an issue?

**Comment by mnataraj92** [comment]
this can be closed
