### ISSUE TITLE
Survey email reminder contact attempts 2-10 not being sent

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/connectApp#300]
Discovered that baseline survey email reminder contact attempts 2-10 are not being sent in dev or prod. 
The conditionality is this: 
RcrtV_Verification_v1r0 = 1 AND 
HdWd_Activepart_v1r0 = 0 AND (meaning they did not refuse all future study activities)
HdRef_Basesrv_v1r0 = 0 AND (meaning they did not refuse the baseline survey)
HdWd_WdConsent_v1r0 = 0 AND (meaning they did not withdraw consent)
SrvLAW_BaseStatus_v1r0 ne 2 (4th module of the baseline survey not submitted) 

Bhaumik responded: I see what is going on, HdRef_Basesrv_v1r0 is nested under "Which activities is the participant refusing? (Select all that apply)" in the participants records, so we will have to use 685002411.994064239 = 0. without the parent reference, the code will not be able to find HdRef_Basesrv_v1r0.

@FrogGirl1123 Nicole, before we fix that in the message specs and retest, a question about variable HdWd_Activepart_v1r0 = 0 which I believe is currently unnested. Do you intend to leave it or nest it?

@bhaumik55231 when we fix the conditionality, will participants get all the past reminders at once (assuming they are X days past verification?)

**Comment by bhaumik55231** [comment]
> when we fix the conditionality, will participants get all the past reminders at once (assuming they are X days past verification?)

@brotzmanmj Unfortunately. Yes, they would get past reminders.

**Comment by brotzmanmj** [comment]
@FrogGirl1123 @bhaumik55231 Abhinav found that the variable HdWd_Activepart_v1r0 is also nested under the refusals in the back end data in firestore. So it seems we'll need to reference this one in the conditionality as 685002411.906417725 = 0 in the email specs. Just the master data dictionary doesn't indicate that this is so. I will open a separate github issue for the data dictionary update for this variable.

**Comment by brotzmanmj** [comment]
@FrogGirl1123 @abhinavjonnada82 Per meeting between Abhinav and Nicole today, this variable HdWd_Activepart_v1r0 = 0 in prod is not nested so Abhinav will correct it in Dev and Stage to not be nested. In the email message specs, no change is needed to the concept ID for this variable.
Also confirmed today by @FrogGirl1123 , the variable for Module 4 status is a default and is being set in prod so our existing logic in the email message schema is fine for this variable.

Next step: After Abhinav unnests HdWd_Activepart_v1r0, Deanna will test in dev updating then conditionality for HdRef_Basesrv_v1r0 to 685002411.994064239 = 0 for survey reminder2 and see if the message gets sent as expected.

**Comment by anthonypetersen** [comment]
is this still an issue? @brotzmanmj @depietrodeanna

**Comment by depietrodeanna** [comment]
No, this will be resolved as we load the new contacts.
