### ISSUE TITLE
Update HdWd_Activepart_v1r0 on master data dictionary

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/connectApp#301]
Variable HdWd_Activepart_v1r0 (concept ID) 906417725 is nested under the refusals in the back end in firestore but is not indicated as such in the master data dictionary. 

@FrogGirl1123 @mnataraj92 this issue is to track the request to update the master data dictionary to change this variable to Secondary Source = Refusal (instead of Withdrawal) and nest under Concept ID 685002411.

Abhinav can provide more information if needed.

**Comment by abhinavjonnada82** [comment]
HdWd_Activepart_v1r0 (906417725) is stored under refusal options (685002411)this is how its stored on the backen
<img width="639" alt="Screen Shot 2022-01-25 at 3 29 03 PM" src="https://user-images.githubusercontent.com/30497847/151068879-25525a16-2b91-47e3-b9eb-f772412ed624.png">
d

**Comment by brotzmanmj** [comment]
@FrogGirl1123 @abhinavjonnada82 @mnataraj92 This is a change in this issue per our meeting today. The variable HdWd_Activepart_v1r0 (concept ID) 906417725 is nested under the refusals in Dev and Stage but not in Prod. We need to stick with how this is in prod. So @abhinavjonnada82 will change this variable in Dev and Stage so that it is a stand-alone variable and not nested. No change is needed to the master data dictionary for this variable.

**Comment by anthonypetersen** [comment]
is this still an issue?

**Comment by abhinavjonnada82** [comment]
I checked in dev/stage/prod firestore (906417725) the variable is standalone as mentioned above & not nested under any variable

**Comment by brotzmanmj** [comment]
Great, can we close this issue then?

**Comment by Davinkjohnson** [comment]
Closing issue as it was verified to be fixed
