### ISSUE TITLE
Functionality and Accessibility of "Forms," "Messages," "My Profile," and "My Samples" tabs

### ISSUE THREAD

**Issue by depietrodeanna** [episphere/connectApp#309]
1. "Forms" tab is unavailable when clicked on before completing consent. Before someone completes the consent process and has forms to view, please use this generic message: "You have no forms available to view."

2. "Messages" tab contains a generic message already. Please edit to match the following:
"You have no messages."

3. "My Profile" tab contains a generic message already. Please edit to match the following:
"You have not completed your profile yet."

4. "My Samples" tab should be **hidden** until after someone consents and submits their user profile. This means that people can view the content on this page before they are verified, but only after they have submitted their profile.

**Comment by anthonypetersen** [comment]
Note to self...

699625233
919254129

**Comment by anthonypetersen** [comment]
this has been pushed to dev

@cunnaneaq @depietrodeanna could one of you confirm this looks good on your end?

**Comment by depietrodeanna** [comment]
Looks good!
