### ISSUE TITLE
Add message after all 4 modules completed

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/connectApp#31]
After the participant is done with all 4 modules, the message in the yellow box should say 'Thank you for completing your first Connect survey! We will be in touch with next steps for the study.' Since modules 2-4 can be completed in any order, we can't trigger the message based on submission of Module 4, but on whichever of modules 2-4 is the last one completed.

**Comment by depietrodeanna** [comment]
The language above is not implemented yet.
