### ISSUE TITLE
Configure direct hyperlink to My Samples page

### ISSUE THREAD

**Issue by depietrodeanna** [episphere/connectApp#310]
For the biospecimen scheduling invitation emails, we need to add hyperlinks to the My Samples page on the PWA (we say, for example, “For more information about donating samples, please visit the MyConnect app.”). In this case, “MyConnect app” will be hyperlinked. 

1. Is it possible to push someone directly to the My Samples page via a specialized hyperlink?
2. How does this work for people who are signed in on the PWA already, vs. those who have to sign in?

**Comment by depietrodeanna** [comment]
@anthonypetersen did we resolve this on our call last week? Can I close?

**Comment by anthonypetersen** [comment]
@depietrodeanna I don't think we actually ended up doing anything, but yes I think we showed that what was happening was what we wanted.
