### ISSUE TITLE
Unsupported browser message modified 

### ISSUE THREAD

**Issue by depietrodeanna** [episphere/connectApp#312]
Confirmed behavior and edited content of message that appears when someone is trying to access the PWA on an unsupported browser (Firefox or Internet Explorer). Screenshots documented here: https://nih.box.com/s/4c7wut6zuwssvakpsuuxde9c3zwrdw1j

New message reads "The MyConnect app is not supported on your browser. Please use Chrome, Safari, or Edge."

**Comment by cusackjm** [comment]
![image](https://user-images.githubusercontent.com/85582895/155738527-5268c8cb-d002-4352-86a5-683cf1b19ecc.png)
Internet explorer message.
