### ISSUE TITLE
Enable download functionality for consent and HIPAA forms

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/connectApp#32]
Add the functionality that enables the download of the consent and HIPAA forms on the app. Forms will be site specific and will be available soon. Check with Abhinav for solution to download form and append the name, date, and version number onto the form.

**Comment by naiyume** [comment]
Awaiting HIPAA forms to be finalized

**Comment by brotzmanmj** [comment]
Site-specific final consent and HIPAA forms will be available after IRB approval of each site. The earliest ones will be for HP and Sanford, hopefully by third week of June.

**Comment by cunnaneaq** [comment]
Have checked the download functionality of the draft forms in dev and the Sanford HIPAA and consent forms in stage.  Brian and I worked to fix the double download of the site forms and the draft page which was brought to our attention by Chun. Health Partners' HIPAA form needs some alignment changes and the HP consent still need to be updated.

I think this is an older issue.  Can we close?

**Comment by brotzmanmj** [comment]
We can close this issue but please open another issue specific to the HP consent and HIPAA forms if there isn't one already

**Comment by cunnaneaq** [comment]
Updated issue created for HP consent and HIPAA form.
https://github.com/episphere/connectApp/issues/228
