### ISSUE TITLE
Add Vulnerability Disclosure link to footer of PWA

### ISSUE THREAD

**Issue by depietrodeanna** [episphere/connectApp#321]
To comply with NIH/HHS guidance, **please add in the footer of the PWA** the text "HHS Vulnerability Disclosure" hyperlinked to this URL: https://www.hhs.gov/vulnerability-disclosure-policy/index.html 

Please list under the "Policies" subheading in the footer (see screenshot of public facing website below)

<img width="644" alt="Screen Shot 2022-03-14 at 4 28 44 PM" src="https://user-images.githubusercontent.com/74061787/158255792-33006abe-bd4b-43a7-92b4-45570aa44fd9.png">

**Comment by anthonypetersen** [comment]
code pushed to dev

**Comment by anthonypetersen** [comment]
can this be closed?
