### ISSUE TITLE
Formatted Biospecimen Table Questions

### ISSUE THREAD

**Issue by wyattks** [episphere/connectApp#326]
We have a question on the table headers.  
Where did the labels on the data file come from? 
Can we update update them to match what is listed in the dashboard?
Also can we have Baseline added to the following labels as we think the date/time is supposed to reflect the Baseline collection:
Column MZ - Date/time Blood Collected
Column NA - Date/time Mouthwash Collected
Column ND - Date/time Urine Collected

We want to make sure we are looking at the correct data.

**Comment by anthonypetersen** [comment]
is this still an issue?

**Comment by wyattks** [comment]
I will close.
