### ISSUE TITLE
Survey status variable needed for Menstrual Cycle Survey

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/connectApp#327]
Hi Madhuri, Nicole requested that we create a variable for Menstrual Cycle Survey Status (not started, started, submitted) just like the other survey flags. It will be a default variable (defaulted to 'not started'). Nicole @FrogGirl1123 will follow up with you about this.

The goal is to get this variable into place to default before Henry Ford launches and loads their ~ 140k eligible frame of patients into prod.

**Comment by mnataraj92** [comment]
the flag & time stamps have been added to the gold standard file
