### ISSUE TITLE
Remove 'Placeholder' in variable labels for Module 1-4 survey flags and times

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/connectApp#328]
If @FrogGirl1123 agrees, suggest we remove the word 'Placeholder -' from the variable labels in the data dictionary and in the format library for the variables associated with Modules 1-4 survey status, time started, and time submitted. Since these are the actual variables that are in use and no longer placeholders (please correct me if I'm wrong).

**Comment by anthonypetersen** [comment]
can we close this now?

**Comment by mnataraj92** [comment]
@anthonypetersen  yep this can be closed
