### ISSUE TITLE
Client side baseline biospecimen survey email sent twice in a row

### ISSUE THREAD

**Issue by depietrodeanna** [episphere/connectApp#329]
Configure the check-in button to only be clickable one time in order to trigger the the first baseline biospecimen survey email. Test account received two emails back to back with the same content because the check in button was pushed two times back to back (near immediate). Participants should only receive one email. Connect ID for the test case is 5826500702.

**Comment by anthonypetersen** [comment]
@depietrodeanna this has been pushed to dev and is ready to test

**Comment by depietrodeanna** [comment]
@anthonypetersen I've been creating test accounts in dev to test biospec survey reminder contacts 3-5, and by default the accounts had to receive this first contact. Only one email has been received so far for each new account I've created. Closing this.
