### ISSUE TITLE
Update and re-order list 'How did you hear about the study'

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/connectApp#33]
We have updated the list of responses for 'How did you hear about the study?' based on user feedback from the last round of testing. The Master Data Dictionary has been updated and the final list in the order they should appear is here. I have noted exactly what has changed and whether the same or new Concept IDs are needed. 

•	Email or text invitation [this used to be 'Email or text from my health care system'; same Concept ID]
•	Letter or brochure in mail
•	Invitation through my patient portal (such as MyChart) [this used to be 'MyChart invitation'; same Concept ID]
•	Phone call invitation  [this option is newly added and needs a Concept ID]
•	Physician or other health care staff
•	Connect research staff at my health care system [this option is newly added and needs a Concept ID]
•	News article or press release about Connect [this used to be just 'News article or press release'; same Concept ID]
•	Health care system newsletter
•	Health care system website 
•	Connect website on Cancer.gov
•	Social media post (on Facebook, Twitter, Instagram, or other channels)
•	Local news, television, or radio station
•	Video
•	Family or friend
•	Another Connect participant
•	Poster, flyer, or sign at my health care system
•	Connect table at public event [this used to be just 'Table at public event; same concept ID]
•	Recorded message [this used to be 'Telephone Hold Message'; same concept ID]
•	Other

**Comment by naiyume** [comment]
Fields added, need to add concept Ids

**Comment by cunnaneaq** [comment]
- 5th bullet: update to say "health care staff" rather than "medical staff"
- 11th bullet: update to say "social media post"

Other changes look great!
