### ISSUE TITLE
No soft check "continue without answering" when submitting grid questions

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/connectApp#331]
For the grid questions in module 2, if you do not answer one of the questions on the page, you can still click "next" and move through the survey without receiving a soft check of "Answer the question" and "Continue without answering."  The screenshot below shows an example of this in the third question on the page.

![image](https://user-images.githubusercontent.com/83971268/161273479-959840e1-df1a-4b61-bddc-d60aae2b4d28.png)

**Comment by anthonypetersen** [comment]
is this still an issue?

**Comment by cusackjm** [comment]
@anthonypetersen fixed
