### ISSUE TITLE
Menstrual cycle survey implentation

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/connectApp#333]
Here is the link to the requirements for the Menstrual Cycle Survey plan 
https://nih.app.box.com/file/662613524300?s=dor2erjg5kcc3180rdtcrndonqueae29

**Comment by anthonypetersen** [comment]
Just to confirm... In the scenario where someone starts this survey and answers "No", when the PWA ends the survey do want the status to be "Started" or "Not Started"?

**Comment by anthonypetersen** [comment]
pushed to dev

**Comment by cusackjm** [comment]
@anthonypetersen Could you update the following in the PWA

- Change heading from "Menstrual Cycle" to "Menstrual Cycle Survey" 
- Change description from "questions about menstrual cycle." to "Questions about the date of your first menstrual period after you donated samples for Connect."

![image](https://user-images.githubusercontent.com/85582895/185462641-b766e02d-1629-4de9-bb87-024e25b4e2e0.png)

**Comment by anthonypetersen** [comment]
@cusackjm pushed to dev

**Comment by cusackjm** [comment]
@anthonypetersen Fixed in dev testing 8/19
