### ISSUE TITLE
Add logic to update "All baseline surveys completed" in PWA

### ISSUE THREAD

**Issue by Davinkjohnson** [episphere/connectApp#335]
Currently, this variable (All baseline surveys completed) is not updated anywhere in our code. Going forward it makes the most sense to check and update this variable after a participant completes each module. Update the code to perform this update.

@anthonypetersen if you think this is something Warren could accomplish I can ask him to look into it as well.

**Comment by anthonypetersen** [comment]
pushed to dev

**Comment by anthonypetersen** [comment]
@cunnaneaq @robertsamm would one of you be able to confirm that this appears to be working?

**Comment by cunnaneaq** [comment]
Seems to be working from what I can see

![Screen Shot 2022-04-14 at 4 49 17 PM](https://user-images.githubusercontent.com/83971268/163472885-15fb5cf6-a185-459e-b631-10180a62e072.png)

**Comment by anthonypetersen** [comment]
can this be closed?

**Comment by anthonypetersen** [comment]
@cunnaneaq

**Comment by cunnaneaq** [comment]
Fine with me
