### ISSUE TITLE
Remove 'change password' option from My Profile tab

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/connectApp#346]
Can you please remove the option to 'change password' from the bottom of the My Profile tab in the PWA of a verified participant?  Participants no longer have the option to create a password to log in to the PWA.  

![Screen Shot 2022-05-09 at 9 09 19 AM](https://user-images.githubusercontent.com/83971268/167416708-564a2527-baa2-4925-9d53-9f1a39ef4ed6.png)

**Comment by anthonypetersen** [comment]
Pushed to dev

**Comment by cunnaneaq** [comment]
Looks good!

![Screen Shot 2022-06-02 at 2 04 26 PM](https://user-images.githubusercontent.com/83971268/171696939-0c67c46e-dcbe-44f8-b2da-3e7131df777f.png)

![Screen Shot 2022-06-02 at 2 04 41 PM](https://user-images.githubusercontent.com/83971268/171696977-0970fbcc-05cc-4e0c-834b-fc16de6b940a.png)
