### ISSUE TITLE
My Profile tab - changed email address not updated in Sign In Information box

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/connectApp#348]
I changed the email address used to sign in to the PWA from signintest@mailinator.com --> signintesting@mailinator.com. 

I was able to log in using the new email address, but the old email address was still showing up in the "Sign in Information" box at the bottom of the My Profile tab (circled in black)

![Screen Shot 2022-05-09 at 3 19 35 PM](https://user-images.githubusercontent.com/83971268/167482004-29573cc9-5ca9-437a-97cc-85b2cc0e80ed.png)

![Screen Shot 2022-05-09 at 3 20 42 PM](https://user-images.githubusercontent.com/83971268/167482268-34f90401-74ac-46d9-93a8-7dd81fc10f92.png)

**Comment by anthonypetersen** [comment]
pushed to dev

**Comment by anthonypetersen** [comment]
@cunnaneaq want to double check this please?

**Comment by brotzmanmj** [comment]
Question about this: Will the fix that you're working on for this actually enable a participant to change their login email on the app after verification?

**Comment by cunnaneaq** [comment]
@brotzmanmj that's a great question.  I messaged Tony yesterday afternoon that I tried to log in with the email address that I changed it to, but wasn't receiving the magic link

**Comment by brotzmanmj** [comment]
@anthonypetersen Let us know what you find, thank you. We have a question from one of the sites about this in prod so I have on my list to respond to them.

**Comment by anthonypetersen** [comment]
@brotzmanmj @cunnaneaq how do we want this to work? I believe it changes your login email as well as the preferred email which is what's displayed on the page.

**Comment by brotzmanmj** [comment]
@anthonypetersen Those should be two separate things, the login email and the preferred email. It shouldn't change both. Do we need a quick call to look at this together?

**Comment by brotzmanmj** [comment]
@anthonypetersen To summarize our discussion, the Sign-In Information email should display just the email they use of logging in to the app/authentication, not the preferred email. Clicking on 'Change Login Email' should only change the login email and not the preferred email.

**Comment by cunnaneaq** [comment]
@anthonypetersen @brotzmanmj Worked well in dev!  I changed the login email and was able to log in with the new email address and the preferred email address remained the same

![Screen Shot 2022-06-14 at 5 22 00 PM](https://user-images.githubusercontent.com/83971268/173691266-b1ec1528-5dde-4cdc-bed2-f19857924b76.png)

**Comment by cunnaneaq** [comment]
and stage!
