### ISSUE TITLE
My Profile tab - no info when mobile phone sign in

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/connectApp#349]
When I signed into the PWA using a mobile phone.  There is no information in the "Sign In Information" box at the bottom of the My Profile tab. 

This box should state that a phone number was used as the mode of sign in along with the number used to sign in.  It is known that this may be a different number than the phone number entered when the participant completes their user profile.

![Screen Shot 2022-05-09 at 3 24 13 PM](https://user-images.githubusercontent.com/83971268/167482683-259534bd-2978-4a88-aa85-30f70bad1fff.png)

**Comment by Davinkjohnson** [comment]
This is in PROD
