### ISSUE TITLE
Fix typos on To Do list in survey descriptions and time estimates

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/connectApp#35]
See the specs for this on the Triggers document in the table at the top : https://nih.app.box.com/file/778353805749?s=kj7ubb8wp6hrm0rsovnsbz3bruu6le2l

**Comment by depietrodeanna** [comment]
Fix text under Medications, Reproductive Health, Exercise, and Sleep. In the description of this section: Questions about your current and past use of medications, your exerciseand sleep habits, and your reproductive health

the words "exercise" "and" are joined together.
