### ISSUE TITLE
Yellow bar message on the Dashboard after submitting the First Survey & Biospecimen Qx

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/connectApp#350]
After I submitted the Biospecimen Qx, the yellow bar message on the Dashboard read:

![Screen Shot 2022-05-11 at 2 37 21 PM](https://user-images.githubusercontent.com/83971268/167940792-6f5b6b36-aa6e-4b63-a540-8704cef12543.png)

**Comment by cunnaneaq** [comment]
Update: I tested this issue further and the yellow bar message shown above is not disappearing after the First Survey is submitted.  This message should disappear after the page is refreshed or a participant signs in again.

@depietrodeanna will work on language for the message that should appear after a participant submits the biospecimen survey.

**Comment by depietrodeanna** [comment]
yellow bar message after completing biospecimen survey (and any other future survey): Thank you for submitting your survey!

**Comment by cunnaneaq** [comment]
Looks good in dev 8/12

**Comment by anthonypetersen** [comment]
is this good to be close now?
