### ISSUE TITLE
Unable to consent in dev and stage

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/connectApp#353]
Erin at HP is having trouble consenting fake participants in dev and stage. Erin reporting the same issue in dev last week and is now having this issue in stage. "I am now trying to get our 4 fake participants ready for testing in STAGE next week and I am having an issue with consent again. This time, in Safari on my iPhone, I can see the check box for consent and the first and last name fields, but I cannot get anything to actually enter. The previous button and hyperlinks are also not functioning." She also downloaded Firefox on her phone but got worse results. Nothing seemed to load.
In Safari:
![image](https://user-images.githubusercontent.com/53540067/169355238-c684041c-b0f8-44de-b93c-3c0f434df24b.png)
In Firefox:
![image](https://user-images.githubusercontent.com/53540067/169355744-a1b3b45e-f05b-4397-9942-f7ffd2a6e2ed.png)
In dev: 
![image](https://user-images.githubusercontent.com/53540067/169355866-5b7c71c1-f725-4aeb-9bef-986eaac23973.png)

**Comment by brotzmanmj** [comment]
Update: Erin confirmed the issue is isolated to phone and iPad. Works OK on laptop. Check rendering of consent on those devices.

**Comment by brotzmanmj** [comment]
One more update from Aileen: 
I had a similar experience to Erin when trying to consent in dev on my iPhone.  I used both Safari and Chrome and when I got to the final consent screen, the PWA stopped loading and I didn’t see most of the screen including the NCI consent docs and the “Yes, I agree to join Connect” box.  

I was able to consent in dev using Safari on my iPad.

**Comment by Davinkjohnson** [comment]
Per Erin's testing this morning. 

I have tried two fake participants in DEV and the system is still acting strangely. There is a significant delay (~15 seconds) to load anything beyond the title section of the Electronic health records release. And once it did load, the consent box could not be clicked/name could not be entered---it is as if the system had frozen. I waited a few minutes in case this just needed time to load with no luck. I then exited the PWA and went back in through the magic link in the email and was then able to consent.

@naiyume can you take another look into this to see if there were any errors maybe captured by Sentry or if it's something you might see in your tests as well?

**Comment by anthonypetersen** [comment]
are we good to close this now?

**Comment by Davinkjohnson** [comment]
Julie tested this on her phone this morning, and it is working again. (Dev and Stage are in sync currently so this verifies the Prod functionality as well.)
