### ISSUE TITLE
Stage notifications not going out

### ISSUE THREAD

**Issue by depietrodeanna** [episphere/connectApp#358]
@anthonypetersen 
Baseline biospecimen survey reminders and first post verification baseline survey reminder not going out in stage. Notification schemas look fine, but test participants are not receiving messages.
 
Here are the Connect IDs I was looking at from HP’s testing: 8015772353 and 7510942563
And if you need more info on these test pts, they are in HP’s testing spreadsheet, the first two test accounts: https://nih.box.com/s/ge5ljaqr8j2z4ildpzzbh0m7t9uc5292

**Comment by anthonypetersen** [comment]
@depietrodeanna can this be closed?
