### ISSUE TITLE
Edit message that appears after submitting a survey

### ISSUE THREAD

**Issue by depietrodeanna** [episphere/connectApp#359]
Edit to language that appears upon survey submission. 

New message should read: "Thank you for submitting your survey. If you are using a shared device, please remember to log out of the MyConnect app and any email accounts you have open."

**Comment by depietrodeanna** [comment]
@anthonypetersen it's the message that appears on the screen right after you submit a survey. It's not a yellow notification bar message.

**Comment by anthonypetersen** [comment]
@depietrodeanna what does it currently say? I'm trying to determine if this is something set by our team or something that's configured by IMS in the modules they deliver.

**Comment by depietrodeanna** [comment]
It currently just says, "Thank you for submitting your survey."

**Comment by anthonypetersen** [comment]
This issue probably needs to go on the Quest board then so IMS can take a look at it @depietrodeanna

**Comment by anthonypetersen** [comment]
are we good to close this now?
