### ISSUE TITLE
eNewsletter

### ISSUE THREAD

**Issue by depietrodeanna** [episphere/connectApp#360]
We need to create a stylized email newsletter with text and images, with hyperlinks to the PWA and public website. Collaborate with @depietrodeanna for content, format, and all questions. This will be configured as a **one time** notification programmed to send to all verified Connect participants on a pre-specified date.

2 pages of the newsletter content will be syndicated from the public website on cancer.gov to the PWA. We can coordinate with OCPL regarding questions. 1 page of the newsletter will direct participants straight to the PWA. We need to discuss a location for this "Did You Know" factoid page on the app. 

Timeline- we plan to submit content to NIH IRB by June 18th and send these emails out to participants by the end of June. We need adequate time to test and program in prod before the end of June (2 weeks minimum).

**Comment by depietrodeanna** [comment]
@abhinavjonnada82 

eNewsletter issue 1 template content:
[Connect_eNewsletter_Issue1_Email.docx](https://github.com/episphere/connectApp/files/9261599/Connect_eNewsletter_Issue1_Email.docx)

Images for each section: 

Lead Image (current placeholder is the group of four people): Factoid (to be updated with real enrollment #s by OCPL): https://nih.box.com/s/b6ekjdx81mn6mrhlyguwahyzlr0val7v

Welcome message: 
![GAUDETheadshot_0](https://user-images.githubusercontent.com/74061787/182905429-114689d2-b587-4b69-b278-34ab1e28a72e.jpeg)


In the Spotlight:
![Roxy Eibergen Photo](https://user-images.githubusercontent.com/74061787/182904772-62ae3fb4-32ed-4660-9e02-483912322069.jpg)

Did You Know: https://nih.box.com/s/ni0cpwnyafrs919quvg4vksiwgr2ndkl

**Comment by anthonypetersen** [comment]
are we good to close this now?
