### ISSUE TITLE
Troubleshoot message issues in production

### ISSUE THREAD

**Issue by depietrodeanna** [episphere/connectApp#367]
On 6/8 we identified several scenarios in which prod messages were not pushed out to participants who met the appropriate conditionality to receive them. This seems to be happening randomly; I have not found a consistent connection between all of the pts who were supposed to receive messages but didn't. 

Below is a sample of Connect IDs and the associated relevant info. Please begin troubleshooting to see if there is anything on the backend or other records that indicate something was wrong and a potential reason messages did not go out as expected:

<img width="758" alt="Screen Shot 2022-06-08 at 3 13 57 PM" src="https://user-images.githubusercontent.com/74061787/172698085-d2b95dda-fbac-48b9-8ae5-e9e96644f2d3.png">

<img width="758" alt="Screen Shot 2022-06-08 at 3 54 11 PM" src="https://user-images.githubusercontent.com/74061787/172705329-78e7b44b-9f8e-4911-a711-b0e673821bce.png">

<img width="759" alt="Screen Shot 2022-06-08 at 3 59 55 PM" src="https://user-images.githubusercontent.com/74061787/172706209-ec631b1b-0f13-48f9-babf-5cedf005f4f5.png">

**Comment by anthonypetersen** [comment]
@depietrodeanna did we resolve these or no?
