### ISSUE TITLE
Derived Age variable missing in Participants Table 

### ISSUE THREAD

**Issue by KELSEYDOWLING7** [episphere/connectApp#377]
D_117249500 - the age derived from the Day, Month and Year isn't currently in the participants table for any environment. Can this be added?

If this is more appropriate in the ConnectFAAS repository please let me know

**Comment by Davinkjohnson** [comment]
@KELSEYDOWLING7 has this been resolved?

**Comment by KELSEYDOWLING7** [comment]
Yes
