### ISSUE TITLE
Update wording on e-consent screens

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/connectApp#39]
Here is the final IRB-approved wording for each of the e-consent screens. 
https://nih.app.box.com/file/779286263344

**Comment by depietrodeanna** [comment]
Language on several eConsent module screens needs to be fixed. 
**Screen 1**: two words not separated by a space. "the" and "environment" in second paragraph. 
**Screen 4**: two words not separated by space. "Connect" and "for" in second line. 
**Screen 4**: progress bar is called "Benefits" but should be called "Leaving." 
**Screen 5**: two words not separated by space. "if" and "you" in second to last paragraph
**Screen 6**: change "identify" to "identity" in second line. 
**Screen 6**: screen is called "Leaving" in progress bar but should be called "Benefits"
**Screen 7**: two words not separated by space. "have" and "any" in third line

At the end on the "You have completed the consent process" screen, remove colon (:) from both lines of text- "Download a copy of your signed consent form" and "Download a copy of your signed health records release form"

**Comment by depietrodeanna** [comment]
Final radio button on eConsent screen 7 (Informed Consent) needs to change from "Yes, I agree" to "Yes, I agree to join Connect" to match language above the radio button

**Comment by depietrodeanna** [comment]
On Thank You screen after submitting consent form and before My Profile, add this sentence at the end of the paragraph of text that starts with _Thank you for interest in the Connect for Cancer Prevention Study_: If you have any questions, please contact the Connect Support Center
