### ISSUE TITLE
Dev: Mod1 not submitting

### ISSUE THREAD

**Issue by robertsamm** [episphere/connectApp#390]
I'm having issues with Module 1 in dev today. I submitted Mod1 for two dev test pts today (Connect ID: 1174237386 and 5553645270) and after I hit submit it takes me back to the to do list dshbrd but still shows the Mod1 as not started and the other sections still greyed out. I went back into Mod1 and it took me back to the beginning of the survey where my answers were saved but I had to pg thru every question to try to submit again. When I hit submit again it did the same thing as before. I didn't have this issue 2 days ago when I was completing the survey in dev.

**Comment by anthonypetersen** [comment]
is this still an issue?

**Comment by robertsamm** [comment]
Nope, this issue occurred around the same time you were pushing updates to module 1 and has been fixed. Closing issue.
