### ISSUE TITLE
Change how 'Cancer History' questions appear on user profile

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/connectApp#40]
On the user profile, put another section (thin gray bar) after Mailing Address right before the question about whether they have ever had cancer. Put a header 'Cancer History' and a sentence to be drafted by Deanna before the cancer history question.

**Comment by depietrodeanna** [comment]
Update language under Cancer History section. Add this intro text under section heading: We are looking for people who have never had cancer to join Connect so we can study the health and behavior patterns that may affect cancer risk in the future. 
 
Revise question to this and add clarification:
Have you ever had invasive cancer?  Yes/No

Insert this text in italics: _If you have or once had non-melanoma skin cancer (like basal cell or squamous cell carcinoma), or a condition that raises cancer risk (such as DCIS, or stage 0 breast cancer), please respond “No” to this question. These conditions are not invasive cancer, and you can still join. We are interested in in learning how these conditions may affect cancer risk and health outcomes in the future._

**Comment by depietrodeanna** [comment]
If someone answers "Yes," the additional questions that display should _not_ be required. These include: year diagnosed, what kind of cancer, and open field for anything else that someone wants to note about their diagnosis.
