### ISSUE TITLE
Edit message that appears on dashboard for accounts marked duplicate 

### ISSUE THREAD

**Issue by depietrodeanna** [episphere/connectApp#416]
Message that appears on the dashboard when someone logs into a duplicate account should be edited to state the following:

Our records show that there is another account linked to your sign in information. Please contact the Connect Support Center by emailing [ConnectSupport@norc.org](mailto:ConnectSupport@norc.org) or calling 1-877-505-0253 so we can help you access the correct account.

**Comment by Davinkjohnson** [comment]
@depietrodeanna Can you please check the below issue to see if this new issue supersedes the old one?

https://github.com/episphere/connect/issues/145

**Comment by depietrodeanna** [comment]
Seems these as separate issues, and I’m not sure the old issue should even be open anymore..

--
Deanna DePietro [C] | Connect Participant Engagement and Communications Coordinator
Division of Cancer Epidemiology and Genetics
National Cancer Institute, National Institutes of Health
E: ***@***.******@***.***>
M: (845) 901-3671
Pronouns<https://www.mypronouns.org/what-and-why>: she/her/ella




From: Davin ***@***.***>
Reply-To: episphere/connectApp ***@***.***>
Date: Wednesday, September 21, 2022 at 11:36 AM
To: episphere/connectApp ***@***.***>
Cc: "DePietro, Deanna (NIH/NCI) [C]" ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [episphere/connectApp] Edit message that appears on dashboard for accounts marked duplicate (Issue #416)


@depietrodeanna<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdepietrodeanna&data=05%7C01%7Cdeanna.depietro%40nih.gov%7C8b3cb21ccd5a42e66b5108da9be70261%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637993713738752845%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=1JI5cWygT0APVV%2BHjNlR1djOlbTtbGI0tSrhd%2F7SwMU%3D&reserved=0> Can you please check the below issue to see if this new issue supersedes the old one?

episphere/connect#145<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fepisphere%2Fconnect%2Fissues%2F145&data=05%7C01%7Cdeanna.depietro%40nih.gov%7C8b3cb21ccd5a42e66b5108da9be70261%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637993713738752845%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=bfX7CVA7JxfV68m4CTeXTRPsYhOWZ15iyOZdgNHPYIA%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fepisphere%2FconnectApp%2Fissues%2F416%23issuecomment-1253881701&data=05%7C01%7Cdeanna.depietro%40nih.gov%7C8b3cb21ccd5a42e66b5108da9be70261%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637993713738752845%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=UCa1MvfooT5qMQOKxACjLPj4xuOMwiEOJNFQfrYimYs%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FARVBPW7GS3X4LUYWAHJNX4DV7MTOBANCNFSM6AAAAAAQSCVRSM&data=05%7C01%7Cdeanna.depietro%40nih.gov%7C8b3cb21ccd5a42e66b5108da9be70261%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C637993713738752845%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=DH0UcP12Q9yzz15f2CZahRFkc2a0md3Jgaiq0pzwhIU%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and are confident the content is safe.

**Comment by anthonypetersen** [comment]
pushed to dev

**Comment by depietrodeanna** [comment]
@cunnaneaq do you have time to create a test account in dev for this this week?

**Comment by cunnaneaq** [comment]
Looks good in dev testing 10/5 - account Connect ID: 1574929778 (AD1NCITest@mailinator.com)
![Screen Shot 2022-10-05 at 11 19 15 AM](https://user-images.githubusercontent.com/83971268/194097880-5545866e-4118-4a2b-a761-c3c1a01c1554.png)

**Comment by anthonypetersen** [comment]
@cunnaneaq this should be in stage now as well

**Comment by cunnaneaq** [comment]
Looks good in stage testing 10/6 - account Connect ID: 6962676565 (ActiveDupTest@mailinator.com)

![Screen Shot 2022-10-06 at 3 39 21 PM](https://user-images.githubusercontent.com/83971268/194403822-5414159e-422b-4608-88c8-675674105f69.png)

**Comment by depietrodeanna** [comment]
@anthonypetersen Can you edit so the phone number is all on one line and @cunnaneaq can retest in stage? This looks great otherwise.

**Comment by anthonypetersen** [comment]
@depietrodeanna @cunnaneaq changes pushed to dev, see images below:

![Screen Shot 2022-10-12 at 3 34 33 PM](https://user-images.githubusercontent.com/18222069/195442754-4622aa66-5bc0-4c3a-94d0-191992ef1403.png)
![Screen Shot 2022-10-12 at 3 34 39 PM](https://user-images.githubusercontent.com/18222069/195442761-0de32eaf-1f70-40e8-8156-373b0c73bc2c.png)

**Comment by cunnaneaq** [comment]
@depietrodeanna @anthonypetersen looks good in dev.  Resized the window and saw the same thing as Tony's screenshots. (happens with the Connect Support email address too)

**Comment by depietrodeanna** [comment]
@anthonypetersen did you make changes or just resize the window? if there are changes to push to stage could you please push those and @cunnaneaq could you test?

**Comment by anthonypetersen** [comment]
@depietrodeanna @cunnaneaq pushed to stage

**Comment by cunnaneaq** [comment]
fixed in stage

**Comment by depietrodeanna** [comment]
Thanks! @anthonypetersen can you push this change to prod in the next round?

**Comment by anthonypetersen** [comment]
will do

**Comment by anthonypetersen** [comment]
this should be in prod now
