### ISSUE TITLE
HP Withdrawal Notification didn't go to site

### ISSUE THREAD

**Issue by robertsamm** [episphere/connectApp#417]
Hello @anthonypetersen, HPs study team let us know this morning that they did not receive the site notification of withdrawal in their study inbox for their participant that withdrew on 9/14 (Connect ID: 9452858145). The notification did come into our ConnectCC inbox successfully though. We received it on 9/14 at 11:23am ET. Can you look into this?

Note: I believe it was HP that did not receive the site notification for data destruction as well, but they have received previous withdrawal notifications successfully.

**Comment by anthonypetersen** [comment]
HP received notifications on recent cases, closing for now.
