### ISSUE TITLE
Fix error message for email address in user profile

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/connectApp#42]
Please fix the wording on the user profile error message from Please enter a email address in this format: name @example.com to Please enter an email address in this format: name @example.com

**Comment by depietrodeanna** [comment]
The above wording only appears if you hover over the email address field. This language does not appear as a red error message. It should display as the other red error messages display. Configure to display when someone includes an incomplete email or inappropriate email format (e.g., no "@")

**Comment by depietrodeanna** [comment]
No error message if the retype preferred email field is left blank. This should state: "Please retype your preferred email address."
