### ISSUE TITLE
Change order of Baseline Modules listed in PWA Dashboard

### ISSUE THREAD

**Issue by cusackjm** [episphere/connectApp#427]
Can you change the order of the modules so that the modules are displayed in the following order:
- (1) Background and Overall Health
- (4) Where you Live and Work
- (2) Medications, Reproductive Health, Exercise, and Sleep
- (3) Smoking, Alcohol, and Sun Exposure

To be clear, we just want to change the **visual order** of the modules **in the Dashboard**. The flags are being retained and nothing is being renumbered.

**Comment by danielruss** [comment]
@anthonypetersen This is a PWA issue.  see: 
I think the relevant code is https://github.com/episphere/connectApp/blob/master/js/shared.js#L859

**Comment by anthonypetersen** [comment]
@danielruss are you sure this is the right line? this is just where we set the URL for each module.

**Comment by danielruss** [comment]
@anthonypetersen  
> are you sure this is the right line?
No. I am sure of nothing.  But it may define the the array of modules (and whether they should be viewed).

**Comment by anthonypetersen** [comment]
change pushed to dev

**Comment by Davinkjohnson** [comment]
@cusackjm @anthonypetersen was this pushed to prod in our latest release?

**Comment by cusackjm** [comment]
yes on 10/26
