### ISSUE TITLE
HFH update content of My Samples page in dev

### ISSUE THREAD

**Issue by depietrodeanna** [episphere/connectApp#432]
Updates needed to existing site-specific My Samples pages to accommodate addition of new specimen donation location:
Changes are tracked in the file below:

Henry Ford Health: https://nih.box.com/s/ppp1rp3ooljceidv17lao3n0tpw9dpom

**Comment by depietrodeanna** [comment]
@anthonypetersen Please update content to correct typos:
Under Parking Instructions- please correct "surface lot" (see full sentence in screenshot)
<img width="642" alt="Screen Shot 2022-11-02 at 9 19 04 AM" src="https://user-images.githubusercontent.com/74061787/199499856-99215534-b8c8-4b45-96ab-5b16bb2b28f4.png">

**Comment by anthonypetersen** [comment]
@depietrodeanna fix pushed to dev

**Comment by depietrodeanna** [comment]
HF had a typo in the document I didn't catch. Please update the first sentence under Parking Instructions (bolded the edit):

Easy, free self-parking is available in the surface lot **in front of** the building.

**Comment by anthonypetersen** [comment]
@depietrodeanna fix pushed to dev

**Comment by depietrodeanna** [comment]
@anthonypetersen Clear to go to prod when convenient

**Comment by depietrodeanna** [comment]
@addiedavis  There are going to be updates to this document before going to prod. Please hold.

**Comment by depietrodeanna** [comment]
@addiedavis please push new updates to the this document in the dev environment: https://nih.box.com/s/ppp1rp3ooljceidv17lao3n0tpw9dpom

**Comment by addiedavis** [comment]
Will do

**Comment by depietrodeanna** [comment]
@addiedavis 
Please edit KPCO's My Samples page in dev. 
Change the hours for calling the Connect Support Center under the final heading (Questions) to the following (changing CT to MT):

6:00 a.m.-8:00 p.m. MT on weekdays and 7:00 a.m.-4:00 p.m. MT on weekends

**Comment by addiedavis** [comment]
Hi @depietrodeanna, the hours for KPCO should be updated in dev

**Comment by depietrodeanna** [comment]
Thanks! I didn't realize I put that comment on the wrong site's github issue. Sorry. 
HFH has reviewed their My Samples page content in dev- looks good and can be moved to stage when you are able @addiedavis

**Comment by depietrodeanna** [comment]
@anthonypetersen and @addiedavis I think this can be closed? I'm fairly certain this is in prod based on a convo in the punch list.

**Comment by depietrodeanna** [comment]
@Davinkjohnson please reassign. Goal to be in prod by Jan 23.

**Comment by anthonypetersen** [comment]
updates pushed for HF, please verify for stage / prod push
