### ISSUE TITLE
eNewsletter 2 

### ISSUE THREAD

**Issue by depietrodeanna** [episphere/connectApp#442]
Timeline goal- first week of Dec in prod

@abhinavjonnada82 begin improvements to eNewsletter email template html and test on various devices/browsers to ensure readability and format look acceptable. Coordinate with @depietrodeanna and @cunnaneaq for testing as needed.

Content for eNewsletter sent to IRB _awaiting approval_

For the eNewsletter email template, we have the three section headers and the following snippets of text under each (note graphics are not yet finalized for all sections yet- will add asap):

What's New
The Connect team is hard at work to grow the study and build impact! [Read More]
Graphic: https://nih.box.com/s/a2sqh8b66lqf19aq1j8hyx4iyu0p0ywy

Meet La’Verne Adams from Kaiser Permanente Northwest
La’Verne shares why bringing voice and information to diverse communities is important for Connect. [Read More]
Graphic: https://nih.box.com/s/oaw282kahjq34qzspgvptm9016wthpq2

Did You Know?
The “winter blues” is real. Each year, about 16.6 million people in the U.S. experience Seasonal Affective Disorder (SAD), also known as the “winter blues,” a type of depression related to the change in seasons. We have tips to help you feel your best this winter. [Read More]
Graphic: https://nih.box.com/s/ni0cpwnyafrs919quvg4vksiwgr2ndkl

Date at the top right of the template will be December 2022

Same ending text and footer:
We want to hear from you! Which topics would you like to see covered in future newsletters? Are you interested in sharing why you joined Connect? Send your feedback to [ConnectSupport@norc.org](mailto:ConnectSupport@norc.org)

Guidance from OCPL for comps that incorporate dark mode design accomodations:
This is the [updated default/light mode version](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Finvis.io%2FV5131EAPHF9N&data=05%7C01%7Cdeanna.depietro%40nih.gov%7C7ab45b155d364a48239d08daa318982e%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638001623267690325%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=HJusNjtIlwntj%2FBv%2FfVal%2BX3zeTUwE%2BmNObaFBvDB7w%3D&reserved=0) where I did some tweaking to the colors like the background, button and headers. I tested the changes out on this [tool](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fproofjump.com%2Fdark-mode-simulator%2F&data=05%7C01%7Cdeanna.depietro%40nih.gov%7C7ab45b155d364a48239d08daa318982e%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638001623267690325%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=jk6%2Fq1y3xHVDPii89p97yAdu6s6wnm2OPKgVd4XHC1I%3D&reserved=0) that simulates full inversion of colors which is what Gmail seems to do. The inverted version also passes 508 for the text.
If possible, we’d recommend creating a [custom theme](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Finvis.io%2F3D131EBA528Z&data=05%7C01%7Cdeanna.depietro%40nih.gov%7C7ab45b155d364a48239d08daa318982e%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638001623267690325%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=jkRpHV%2FysA%2FAe03A5n4dl8zt3O2mpkn9tBDwmtHa3ls%3D&reserved=0) for dark mode so that when email clients accept those, the users would see the styles we’ve defined for dark mode specifically. This would involve adding code into the email, and I think the Litmus resource you shared explains how to do this, or [their web page on it](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.litmus.com%2Fblog%2Fthe-ultimate-guide-to-dark-mode-for-email-marketers%2F&data=05%7C01%7Cdeanna.depietro%40nih.gov%7C7ab45b155d364a48239d08daa318982e%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638001623267690325%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=tfsbWJkJtGmdy21ze1uPoqxREsDTF3yGIzmAZmgkvE8%3D&reserved=0).
On Invision, the development team should be able to view some notes in the comments mode that call out the styles that would change.

**Comment by Davinkjohnson** [comment]
@de can this be closed?

**Comment by anthonypetersen** [comment]
@depietrodeanna
