### ISSUE TITLE
Update four KP My Samples pages in dev

### ISSUE THREAD

**Issue by depietrodeanna** [episphere/connectApp#447]
@anthonypetersen Please update each of the four KP site My Samples pages in **dev** for the SMs to review:

Clean pages available here:

KPGA: https://nih.box.com/s/9bkqifdw5zz6kleaj6j12167d0hscofc
KPHI: https://nih.box.com/s/tmxtgx1hh461fwgra3jerbts3bbd3ug7
KPCO: https://nih.box.com/s/p0o37qk0ao4zou37korimmxdq6ki06gb
KPNW: https://nih.box.com/s/k9xap14sgt11wq184dwpl03clkgykog7

**Comment by addiedavis** [comment]
Hi @depietrodeanna, these are currently in dev.

**Comment by depietrodeanna** [comment]
@addiedavis The KP Study Manager is not seeing the updates in dev- they are still seeing the old message that says "We plan to begin collecting samples in early 2023..." Could you please confirm the updates are pushed to dev for the KP My Samples pages? There are four pages total (you can skip KPHI for now)

**Comment by anthonypetersen** [comment]
@depietrodeanna can you please provide the account they are using for testing on their end?

**Comment by depietrodeanna** [comment]
@addiedavis @anthonypetersen 
Here are the Connect IDs in dev:
2038073291
2236339756
5827483205
8549113662

All are test accounts from one of the KP sites

**Comment by anthonypetersen** [comment]
@depietrodeanna I provided Addie with the incorrect CIDs, we will let you know when this is corrected

**Comment by addiedavis** [comment]
The corrected CIDs are in DEV along with the updates for the Henry Ford location

**Comment by depietrodeanna** [comment]
Thanks Tony and Addie. I'll follow up after the SMs at those sites have a chance to review.

**Comment by depietrodeanna** [comment]
@addiedavis KPNW, GA, and CO My Samples pages ready for stage push.

**Comment by depietrodeanna** [comment]
@Davinkjohnson please reassign. Goal is to get in production by Jan 23 the latest.

**Comment by anthonypetersen** [comment]
work is done and ready for production, going in with next prod push

**Comment by depietrodeanna** [comment]
@Davinkjohnson There is one sentence to remove in each of the KP pages before moving to prod if possible- all files are tracked. The decision has been made to leave out any specifics around times/days to donate samples. If these are moved to dev I can check the content quickly without having to go through the SMs at KP. Tagging @ramavavi here- Davin can let us know if someone else on the team should make these updates.
KPGA: https://nih.box.com/s/9bkqifdw5zz6kleaj6j12167d0hscofc
KPHI: https://nih.box.com/s/tmxtgx1hh461fwgra3jerbts3bbd3ug7
KPCO: https://nih.box.com/s/p0o37qk0ao4zou37korimmxdq6ki06gb
KPNW: https://nih.box.com/s/k9xap14sgt11wq184dwpl03clkgykog7

**Comment by Davinkjohnson** [comment]
@depietrodeanna can you please confirm that these look good in DEV now?

**Comment by Davinkjohnson** [comment]
This is ready for Stage

**Comment by Davinkjohnson** [comment]
This was approved in stage. Ready for PROD

**Comment by anthonypetersen** [comment]
in production
