### ISSUE TITLE
Update UC My Samples page content

### ISSUE THREAD

**Issue by depietrodeanna** [episphere/connectApp#459]
@addiedavis 
Please update UC's My Samples content starting in dev with changes tracked in this document: https://nih.box.com/s/mkipmbpsdz36hgrjuk8iev564gkpr2v0

**Comment by depietrodeanna** [comment]
@Davinkjohnson  please reassign. Goal to be in prod Jan 23.

**Comment by depietrodeanna** [comment]
@ramavavi are changes for this page pushed to dev?

**Comment by Davinkjohnson** [comment]
@depietrodeanna Can you please confirm this is good in DEV?

**Comment by Davinkjohnson** [comment]
Deanna confirmed this is ready for Stage

**Comment by Davinkjohnson** [comment]
This was approved in stage. Ready for PROD

**Comment by anthonypetersen** [comment]
in production
