### ISSUE TITLE
Update Text on Account Creation Page

### ISSUE THREAD

**Issue by Davinkjohnson** [episphere/connectApp#469]
On the "Create An Account" page, add the following text. 

Connect is a long-term study. Please use an email that you will be able to access in the future. Avoid using a work email if possible.

**Comment by depietrodeanna** [comment]
![image](https://user-images.githubusercontent.com/74061787/217064500-c5f409db-8a67-437d-ba83-902d662f180f.png)
Insert text under the space provided to enter an email address.

**Comment by Davinkjohnson** [comment]
this is in PROD
