### ISSUE TITLE
PWA - Connect PI Change

### ISSUE THREAD

**Issue by robertsamm** [episphere/connectApp#491]
For the Connect PI change, we have to upload new versions of the site-specific Consent and HIPAA Authorization forms to the PWA and SMDB that have the name of the new PI on them. We'll need to be careful to make sure that anyone consented prior to version 2 receives version 1 in the signed forms and anyone that consents after version 2 gets version 2 in the signed forms. The IRB also changed the versioning structure so Version 1=V1.0 and Version 2=V0.02. The IRB is still reviewing these forms so will need to work with fake test forms in dev for now.

Consent version: RcrtCS_Version_v1r0
HIPAA version: RcrtCS_HIPAAVer_v1r0

Here's where this is affected on the PWA:

1. Downloadable unsigned PDFs for Consent and HIPAA forms on the consent signing page for each site
2. HTML display box of Consent and HIPAA forms on the consent signing page for each site
3. Downloadable signed PDFs of Consent and HIPAA forms on the next page after signing for each site
4. Downloadable signed PDFs of Consent and HIPAA forms on the ‘MyForms’ page for each site
5. Will need to display current signed versions for anyone who signed the forms by version # on the MyForms page.

Organizational doc on Box for Connect PI change: https://nih.app.box.com/file/1170318838027

**Comment by robertsamm** [comment]
Related SMDB github issue: https://github.com/episphere/dashboard/issues/496

**Comment by Davinkjohnson** [comment]
This is in PROD

**Comment by anthonypetersen** [comment]
> This is in PROD

PROD!
