### ISSUE TITLE
Missing timestamp of first time sign-in (CID 335767902)

### ISSUE THREAD

**Issue by we-ai** [episphere/connectApp#497]
Some participant data don't have timestamp of first time sign-in (concept ID: 335767902), as described by @mnataraj92 in issue [#612](https://github.com/episphere/connect/issues/612).

**Comment by mnataraj92** [comment]
@brotzmanmj, @we-ai  has implemented a fix in dev for the missing sign-in time stamps for those that have signed in. I will check the data in BQ tomorrow once it updates to confirm this.

**Comment by mnataraj92** [comment]
this is resolved in dev.

**Comment by Davinkjohnson** [comment]
This was addressed in the May release
