### ISSUE TITLE
Consent Submission Page - Submit without agree 

### ISSUE THREAD

**Issue by dbakumar** [episphere/connectApp#53]
We are able to click "Submit" button without check box on  "Yes, I agree to join Connect" and nothing happen.  It may helpful to show some validation error message.

**Comment by depietrodeanna** [comment]
Add this error message: "Please check this box to add your electronic signature"

**Comment by cunnaneaq** [comment]
Looks good!

![Screen Shot 2021-08-11 at 9 28 16 AM](https://user-images.githubusercontent.com/83971268/129037451-9927c2c0-b35c-4555-8e74-fecd0502dbc2.png)
