### ISSUE TITLE
Active Participant Connect Web Site launch - with token

### ISSUE THREAD

**Issue by dbakumar** [episphere/connectApp#54]
When the active participant launch URL which send through email or text from IHCS site,  the page show few login option. This is not clear what to do after seeing different signin options.  The page should have some information about study and place to Join/ sign option display.

![test](https://user-images.githubusercontent.com/4921186/114754368-1c0b1480-9d1e-11eb-85ae-9c4df5b9cab4.jpg)

**Comment by brotzmanmj** [comment]
This is odd. The active participant URL should take them to the home page which has the information about the study and the join | log in options. Should we check the URL they are using? Or is this a holdover from an old version of the app?
