### ISSUE TITLE
Content for COVID-19 Survey description

### ISSUE THREAD

**Issue by depietrodeanna** [episphere/connectApp#558]
Davin, could you coordinate with your team to implement the content below as the description for the new COVID-19 Survey on the PWA dashboard in dev? We just need to leave a placeholder for estimated time to complete (like other surveys have), to be determined by testers. 

Title: COVID-19 Survey

_Questions about your history of COVID-19, including any vaccinations you may have received and details about times you may have gotten sick with COVID-19._

**Comment by anthonypetersen** [comment]
From https://github.com/episphere/connect/issues/645 :

COVID survey will be triggered upon giving a baseline research collection or baseline clinical collection utilizing the same trigger that we currently use to trigger the Biospecimen BUM or BU survey, respectively.

**Comment by depietrodeanna** [comment]
COVID Survey should remain on dashboard until complete (indefinitely).

**Comment by jhflorey** [comment]
@anthonypetersen @depietrodeanna  thanks for your informations

**Comment by depietrodeanna** [comment]
@jhflorey Please update the COVID-19 Survey title and description to the following (adding "Survey" to the title and changing description to start with just "Questions" to match the way the other surveys appear).

Title: COVID-19 Survey

_Questions about your history of COVID-19, including any vaccinations you may have received and details about times you may have gotten sick with COVID-19._

**Comment by jhflorey** [comment]
got it @depietrodeanna
