### ISSUE TITLE
Survey order

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/connectApp#563]
Survey order (upon adding COVID survey): Specify order to appear: Biospecimen survey on top, then modules 1-4, then COVID survey, then SSN survey.

**Comment by Davinkjohnson** [comment]
Should have PR for this today.

**Comment by depietrodeanna** [comment]
@Davinkjohnson @jhflorey This is good in dev.

**Comment by cunnaneaq** [comment]
Research collection account - biospecimen survey at the top, mods 1-4, SSN, COVID 
Is it OK that SSN is above COVID?

**Comment by Davinkjohnson** [comment]
@cunnaneaq can you please share the CID for the test participant you're seeing the different order for?

**Comment by cunnaneaq** [comment]
Connect ID: 8754321335
I didn't start any surveys - this was the order I saw upon signing into the PWA right after the survey became available.  Screenshot for reference:

![Screenshot 2023-07-26 at 2 19 12 PM](https://github.com/episphere/connectApp/assets/83971268/db8bf094-0015-4031-8f45-dfea09dffb2a)

**Comment by jhflorey** [comment]
@cunnaneaq as the confirmation form Deanna the covid survey has to be below ssn
<img width="1066" alt="image" src="https://github.com/episphere/connectApp/assets/24559107/e518ae31-5285-4f58-851a-961f82d71c45">

**Comment by jhflorey** [comment]
@cunnaneaq  as the requirement, the COVID-19 Survey will be displayed along with the Blood/Urine/Mouthwash Survey or Baseline Blood and Urine Sample Survey. 
 
![image](https://github.com/episphere/connectApp/assets/24559107/6b541641-3b04-4f72-8888-a4d4939fad87)

I found the participant 8754321335 had check-in complete baseline


<img width="422" alt="image" src="https://github.com/episphere/connectApp/assets/24559107/38eb9260-64d9-4d63-af6a-e34967e4a650">

@depietrodeanna @cusackjm please help confirm for this case.

**Comment by Davinkjohnson** [comment]
@jhflorey the trigger logic you described and shared the code for looks correct. The COVID survey should appear at the same time as the biospecimen survey (it should just be in the spot further down the to-do list as was confirmed above).
