### ISSUE TITLE
Marshfield pt that signed in is missing sign-in time

### ISSUE THREAD

**Issue by mnataraj92** [episphere/connectApp#566]
In the QC report that Jake ran today (6/5/23), there is a Marshfield pt (Connect ID 6588527958) that has signed in (d_230663853 = 353358909), but is missing sign-in time (d_335767902).

**Comment by we-ai** [comment]
I can confirm above info.
In addition, based on my check now (10:40am, 6-6), there're another 2 participants signed in with missing sign-in timestamp (d_335767902). One has Connect_ID=5110442023 , another has no Connect_ID (state.uid=FJbx9MUkhXM7bHhl1CO2hQ9vXJx1).

**Comment by brotzmanmj** [comment]
Thanks for confirming. That is so odd. Warren, please let us know what you find about why the sign in time is not always being captured.

**Comment by Davinkjohnson** [comment]
Merged in the June release
