### ISSUE TITLE
Update language in Sign-in flow

### ISSUE THREAD

**Issue by Davinkjohnson** [episphere/connectApp#570]
During the sign-in/log in workflow participants first have to find their valid account. the current message for when a login method is not recognized could be more clear. Please update the language above the “Use another account?” and “Don’t have an account?” text to read the following:

“If you’re having trouble signing in or don’t remember your account information, please contact the Connect Support Center at 1-866-462-6621 or [ConnectStudy@norc.org](mailto:ConnectStudy@norc.org)  before creating a new account.”

**Comment by JoeArmani** [comment]
This is now merged to dev.

**Comment by depietrodeanna** [comment]
This looks good in dev @Davinkjohnson
