### ISSUE TITLE
Edit language in duplicate account message

### ISSUE THREAD

**Issue by depietrodeanna** [episphere/connectApp#582]
See previous issue: https://github.com/episphere/connectApp/issues/416#issue-1380953779
For current scenarios in which this would display, edit language to the following:
Our records show that you already have another account with a different email or phone number. Please try signing in again. Contact the Connect Support Center by emailing [ConnectSupport@norc.org](mailto:ConnectSupport@norc.org) or calling 1-877-505-0253 if you need help accessing your account.

This is high priority after the upcoming prod release (scheduled for week of June 26).

**Comment by depietrodeanna** [comment]
@cunnaneaq tested in dev. Language matches.
![MicrosoftTeams-image (1)](https://github.com/episphere/connectApp/assets/74061787/5c03d405-1683-4eb3-bbbf-3cd76c7dea0b)

**Comment by cunnaneaq** [comment]
Looks good - Language updated in dev and stage testing

![Screenshot 2023-07-24 at 5 32 54 PM](https://github.com/episphere/connectApp/assets/83971268/2b43dfc2-499b-48de-b9d4-5305ee218714)
