### ISSUE TITLE
Verify Email  - Text suggestion

### ISSUE THREAD

**Issue by dbakumar** [episphere/connectApp#59]
Suggestion for the screen the screen following hitting the ‘Verify email” button---It may be helpful to leave a note for those who may want to participate to check their junk/spam folder in their email. Not being able to find the verification email may make someone frustrated, and they even may not want to participate

**Comment by miagaudet** [comment]
@depietrodeanna

**Comment by miagaudet** [comment]
@dbakumar -- could you go back and retest when you get a chance. We see the message displayed that guides the users through the next steps.
