### ISSUE TITLE
Edits to electronic consent final signing screen 

### ISSUE THREAD

**Issue by depietrodeanna** [episphere/connectApp#596]
Edit Informed Consent screen in the electronic consent series that displays the consent and HIPAA forms and instructs the recruit to sign the forms digitally. Edits tracked below:

<img width="708" alt="Screenshot 2023-07-06 at 10 36 48 AM" src="https://github.com/episphere/connectApp/assets/74061787/dfb967be-fc33-4fd0-8ddf-a4d0b096874d">

<img width="760" alt="Screenshot 2023-07-06 at 10 37 08 AM" src="https://github.com/episphere/connectApp/assets/74061787/06c524bc-8c87-4553-998b-c521c3892f99">

**Comment by depietrodeanna** [comment]
@Davinkjohnson checked stage- looks good.

**Comment by anthonypetersen** [comment]
can this be closed? @depietrodeanna

**Comment by depietrodeanna** [comment]
Moved to prod in July release
