### ISSUE TITLE
Update MF MySamples page

### ISSUE THREAD

**Issue by brotzmanmj** [episphere/connectApp#598]
The updates to the MySamples pages for the July release are here in track changes: https://nih.app.box.com/file/786047073355?s=6wwbw9bkvevmpk0v9d053h8mokb7jm0d

They have added a new collection location (Minocqua) and have removed the guidance about masking the section on Scheduling Information since that is no longer required at their health care system.

**Comment by depietrodeanna** [comment]
Good in dev and ready for stage @Davinkjohnson

**Comment by depietrodeanna** [comment]
Asked MF to review in Stage.

**Comment by depietrodeanna** [comment]
@Davinkjohnson Tammy checked in Stage. Good to go to prod.
