### ISSUE TITLE
Background and Overall Health survey- Question not displayed

### ISSUE THREAD

**Issue by dbakumar** [episphere/connectApp#60]
Background and Overall Health survey- One of the questions did not populate for a first-time user. The rest of the mock questions did appear correctly.

![ttt](https://user-images.githubusercontent.com/4921186/115921290-e7dfd400-a440-11eb-877c-d62235c7f63b.jpg)

**Comment by brotzmanmj** [comment]
Team- do we know if this was the SOCCR question? If so, have we fixed the issue with that question and has it been retested?

**Comment by anthonypetersen** [comment]
@brotzmanmj can this be closed? it seems a little dated
