### ISSUE TITLE
Issue with Firefox

### ISSUE THREAD

**Issue by bhaumik55231** [episphere/connectApp#62]
When a user comes in with a token in the URL - https://episphere.github.io/connectApp/?token=<token>  the GUI stops responding in firefox.

**Comment by anthonypetersen** [comment]
@cusackjm @cunnaneaq do we ever test in Firefox?

**Comment by cusackjm** [comment]
@anthonypetersen I have not tested this in firefox

**Comment by cunnaneaq** [comment]
@anthonypetersen same as Julie.  How would we go about this?  Test as an active recruit with a token/PIN in firefox?

**Comment by anthonypetersen** [comment]
I would assume we just need to make sure the magic link works as expected in Firefox... It looks like this issue precedes the magic link.

**Comment by cunnaneaq** [comment]
OK, I just tested and was able to sign in to MyConnect in stage using Firefox by clicking on the magic link from a gmail account.  Also tested using a mailinator account.
