### ISSUE TITLE
Consent Screens for Mobile User (iPhone)

### ISSUE THREAD

**Issue by sarah-hague** [episphere/connectApp#63]
While navigating through consent screens on iPhone 8 - Chrome; I was brought to the middle of the next page after selecting next.  I would have thought users should be brought to the top of the next page so no content is accidentally missed while clicking through the pre-consent section. 
Screenshot examples attached.
![IMG_6882](https://user-images.githubusercontent.com/58482976/117195785-54e15b00-adab-11eb-95e1-1d6796e1bf96.jpg)
![IMG_6884](https://user-images.githubusercontent.com/58482976/117195806-5ad73c00-adab-11eb-8e9e-35f58fd04464.jpg)

**Comment by depietrodeanna** [comment]
Issue added elsewhere
