### ISSUE TITLE
Consent Name Boxes - Mobile (iPhone)

### ISSUE THREAD

**Issue by sarah-hague** [episphere/connectApp#64]
When signing name on consent, the field boxes were cramped and box titles were overlapping and suffix box was not aligned.  Additionally, my use case had a particularly long last name which did allow for the entire last name to be visible.  Since these fields are routed to the User Profile and cannot be changed by the user, it would be nice to see the entire field to ensure no spelling errors were inadvertently made.
Screenshots attached.
![IMG_6885](https://user-images.githubusercontent.com/58482976/117196110-b43f6b00-adab-11eb-9798-dfa32c45dccd.jpg)
![IMG_6886](https://user-images.githubusercontent.com/58482976/117196117-b6092e80-adab-11eb-93a8-12b2c032211a.jpg)

**Comment by cunnaneaq** [comment]
confirmed fixed.
