### ISSUE TITLE
Add support center phone number where this is a placeholder

### ISSUE THREAD

**Issue by depietrodeanna** [episphere/connectApp#67]
Add support center phone number where it appears as placeholder xxx-xxx-xxxx
1-877-505-0253

This appears on "Support" page and on consent process screens.

**Comment by depietrodeanna** [comment]
Phone number is still missing from the user profile page at the top and on the Support page.

**Comment by cunnaneaq** [comment]
The phone number on the "Support page" is correct.  The phone number option has been removed from the consent process screen altogether.  Please add 1-877-505-0253 on to the consent process screens.

**Comment by depietrodeanna** [comment]
During the consent process (all screens before signing and submitting the actual consent and HIPAA authorization forms), please replace the current Connect Support Center phone number with this updated phone number: 1-866-462-6621
