### ISSUE TITLE
Update color scheme Connect icon displayed with download on device

### ISSUE THREAD

**Issue by miagaudet** [episphere/connectApp#73]
![image](https://user-images.githubusercontent.com/61757781/118041879-5974b900-b341-11eb-90a6-e939371da5f0.png)

**Comment by depietrodeanna** [comment]
Please use favicon from this folder: https://nih.box.com/s/ncl6lti84yj5aa7fhjumskc33mqx77c5

**Comment by depietrodeanna** [comment]
512x512px version: https://nih.box.com/s/97em66loxe56itbv0hyr39fwc7lfa2a9

**Comment by cusackjm** [comment]
![image](https://user-images.githubusercontent.com/85582895/123969562-5895f600-d986-11eb-9b93-6c811e5b59d6.png)
Confirmed that Connect Icon displayed on download has updated color scheme
