### ISSUE TITLE
Correct message after completing Module 1.

### ISSUE THREAD

**Issue by miagaudet** [episphere/connectApp#74]
@naiyume and @depietrodeanna,

After verification and completing my first module, the verification messages (see below) was still displayed. Is this an error (@naiyume) or a missing requirement (@depietrodeanna)?

Great news! We have confirmed that you are eligible for the Connect for Cancer Prevention Study. You are now an official Connect participant.
The next step is to complete your first Connect survey
Questions? Please contact the Connect Support Center [MyConnect.cancer.gov/support]

**Comment by depietrodeanna** [comment]
Partly correct. Michelle and I updated the messaging that appears post-verification for various states of survey completion in this document: https://nih.box.com/s/n0biiy75k1eew5j5pyjnrmhhxgsktoin

Brian, please update all of the messaging for post-verification- this is the second table in this document, labeled.

The message that Mia is seeing after finishing the first section of the survey is missing the sentence, "Thank you for being a part of Connect and for your commitment to help us learn more about how to prevent cancer." We also need to remove the "Questions? Please contact..." line. 

If you logged out after completing the first module and signed back in, you should only see this message: "Please complete your first Connect survey. Thank you for being a part of Connect."

Brian, all of these conditions and their associated messaged are outlined in the document linked above. Please let me know if you have questions.

**Comment by cunnaneaq** [comment]
After completing 1 module of the first survey the message I received is, "Please complete your first Connect survey" "Thank you for being a part of Connect."

From the conversation above, it seems like this is correct for when I log out and log back in.  But when continuing on from the verification page it should say "The next step is to complete your first Connect survey" "Thank you for being a part of Connect and for your commitment to help us learn more about how to prevent cancer."  This is listed under [all] in the table in the document that Deanna attached.

"Questions? Please contact...." has been removed correctly.
