### ISSUE TITLE
Fix suffix field on user profile

### ISSUE THREAD

**Issue by depietrodeanna** [episphere/connectApp#77]
When selecting a suffix from the dropdown list of user profile and submitting, the suffix field displays as a string of numbers rather than the actual suffix (e.g., Jr). Please configure to display appropriate suffix

**Comment by cunnaneaq** [comment]
In the "My Profile" page after the user profile has been created with a suffix, it appears as "undefined" rather than "Jr."

**Comment by depietrodeanna** [comment]
Suffix is still appearing as "undefined" on the My Profile page of the app (after submitting user profile and navigating to My Profile page)
