### ISSUE TITLE
Change message when receiving phone verification code

### ISSUE THREAD

**Issue by miagaudet** [episphere/connectApp#79]
Current message reads "XXXXXX is your verification code for episphere.github.io." 

Please change to read "XXXXXX is your verification code for MyConnect."

**Comment by cusackjm** [comment]
Message now states "123456 is your verification code for myconnect-stage.cancer.gov" is this ok?

**Comment by Davinkjohnson** [comment]
Brian Checking with Bhaumik for more information

**Comment by cunnaneaq** [comment]
The first text message is when signing-in in dev and the second text message is when signing-in in stage.  The stage link is correct and brings you to the MyConnect home page.  The dev link brings you to the episphere main site.  As discussed with @brotzmanmj and @Davinkjohnson, this is resolved and the link should continue to match the tier when in production.

![IMG-9645](https://user-images.githubusercontent.com/83971268/134959539-523e412b-0acc-4456-adb5-7934c2a74923.PNG)
