### ISSUE TITLE
Consent form window optimization

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/connectApp#88]
When the consent form is in a smaller browser window, have to scroll in both directions in order to read the entire document.  It is suggested that the consent forms be optimized in order to fit the size of the browser window.

**Comment by anthonypetersen** [comment]
@cunnaneaq is this still an issue now that the consent changes have gone in?

**Comment by cusackjm** [comment]
@anthonypetersen you still have to scroll both ways
