### ISSUE TITLE
HIPAA form and consent download - mobile phone

### ISSUE THREAD

**Issue by cunnaneaq** [episphere/connectApp#98]
Using Safari on an iPhone - when downloading copies of the HIPAA form and the consent, the forms open in the same tab.  Is it possible for these forms to open in a new tab?

**Comment by Davinkjohnson** [comment]
Brian collaborating with Abhinav on this.

**Comment by anthonypetersen** [comment]
Is this still an issue?

**Comment by cusackjm** [comment]
@anthonypetersen they still open in the same tab

**Comment by we-ai** [comment]
This can be done without code change. When using an iPhone to download a consent form, press and hold on the download link, then a popup menu will appear. You can choose "Open in New Tab" or other options to start the download.

**Comment by cusackjm** [comment]
@we-ai I don't think the Connect population is aware of this or would know how to do this

**Comment by cusackjm** [comment]
@we-ai still opening in same tab on Safari browser on iPad

**Comment by we-ai** [comment]
PR #486 needs to be tested on Windows desktop or laptop with touchscreens, to make sure the download links work as expected.

**Comment by cusackjm** [comment]
confirmed fix on iPad

**Comment by cunnaneaq** [comment]
Stage testing 3/21/23 - in Safari on an iPhone.  Consent and HIPAA forms opened in a separate tab for the unsigned forms, but not for the signed forms.

**Comment by we-ai** [comment]
Opening a signed form in new tab can be implemented before next dev to stage sync.

**Comment by cunnaneaq** [comment]
The unsigned and signed consent and HIPAA forms are opening in a separate tab, but for the signed forms on the screen immediately post-consent and in the "forms" tab, I have to click on the link twice for it to open.

**Comment by we-ai** [comment]
The double-tap issue is caused by the way iPhone/iPad handles taps on a link. [Here](https://stackoverflow.com/questions/3038898/ipad-iphone-hover-problem-causes-the-user-to-double-click-a-link) is one related post.

**Comment by cunnaneaq** [comment]
@we-ai OK, do you think we should move this along as is?

**Comment by we-ai** [comment]
@cunnaneaq We can move on, and I'll fix this issue later.
